/** City/region aliases -> canonical city names for resolver lookup
 *  Migrated to Entity.aliases in entities.ts — kept as empty export for compatibility */
export const CITY_ALIASES: Record<string, string> = {}

/** US states -> IANA timezone (for the primary/most populous city) */
export const US_STATE_TIMEZONES: Record<string, string> = {
  'california': 'America/Los_Angeles',
  'ca': 'America/Los_Angeles',
  'oregon': 'America/Los_Angeles',
  'washington state': 'America/Los_Angeles',
  'nevada': 'America/Los_Angeles',
  'new york state': 'America/New_York',
  'massachusetts': 'America/New_York',
  'florida': 'America/New_York',
  'georgia': 'America/New_York',
  'pennsylvania': 'America/New_York',
  'virginia': 'America/New_York',
  'north carolina': 'America/New_York',
  'south carolina': 'America/New_York',
  'new jersey': 'America/New_York',
  'connecticut': 'America/New_York',
  'maryland': 'America/New_York',
  'maine': 'America/New_York',
  'vermont': 'America/New_York',
  'new hampshire': 'America/New_York',
  'rhode island': 'America/New_York',
  'delaware': 'America/New_York',
  'ohio': 'America/New_York',
  'michigan': 'America/New_York',
  'west virginia': 'America/New_York',
  'illinois': 'America/Chicago',
  'texas': 'America/Chicago',
  'minnesota': 'America/Chicago',
  'wisconsin': 'America/Chicago',
  'iowa': 'America/Chicago',
  'missouri': 'America/Chicago',
  'arkansas': 'America/Chicago',
  'louisiana': 'America/Chicago',
  'mississippi': 'America/Chicago',
  'alabama': 'America/Chicago',
  'tennessee': 'America/Chicago',
  'kansas': 'America/Chicago',
  'nebraska': 'America/Chicago',
  'oklahoma': 'America/Chicago',
  'indiana': 'America/New_York',
  'colorado': 'America/Denver',
  'arizona': 'America/Phoenix',
  'utah': 'America/Denver',
  'montana': 'America/Denver',
  'wyoming': 'America/Denver',
  'new mexico': 'America/Denver',
  'idaho': 'America/Boise',
  'hawaii': 'Pacific/Honolulu',
  'alaska': 'America/Anchorage',
  // Informal region names
  'east coast': 'America/New_York',
  'west coast': 'America/Los_Angeles',
  'midwest': 'America/Chicago',
  'mountain': 'America/Denver',
  'pacific': 'America/Los_Angeles',
  'eastern': 'America/New_York',
  'central': 'America/Chicago',
  'mountain time': 'America/Denver',
  'pacific time': 'America/Los_Angeles',
  'eastern time': 'America/New_York',
  'central time': 'America/Chicago',
}
