import { normalize } from './resolver'

export interface CityEntity {
  slug: string
  displayName: string
  country: string
  countryCode: string
  iana: string
  lat: number
  lng: number
  aliases: string[]
  wikidataId: string | null
  vibes: string[] | null
  svgCitiesSlug: string | null
}

const CITY_ENTITIES: readonly CityEntity[] = [
  // --- North America ---
  {
    slug: 'new-york',
    displayName: 'New York',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 40.75,
    lng: -73.98,
    aliases: ['nyc', 'ny'],
    wikidataId: null,
    vibes: ['electric', 'hustling', 'bold'],
    svgCitiesSlug: 'us-new-york',
  },
  {
    slug: 'los-angeles',
    displayName: 'Los Angeles',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 33.99,
    lng: -118.18,
    aliases: ['la'],
    wikidataId: null,
    vibes: ['laid-back', 'sun-kissed', 'dreamy'],
    svgCitiesSlug: 'us-los-angeles',
  },
  {
    slug: 'chicago',
    displayName: 'Chicago',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 41.83,
    lng: -87.75,
    aliases: ['chi'],
    wikidataId: null,
    vibes: ['gritty', 'soulful', 'windswept'],
    svgCitiesSlug: 'us-chicago',
  },
  {
    slug: 'san-francisco',
    displayName: 'San Francisco',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 37.74,
    lng: -122.46,
    aliases: ['sf', 'san fran'],
    wikidataId: null,
    vibes: ['foggy', 'inventive', 'free-spirited'],
    svgCitiesSlug: 'us-san-francisco',
  },
  {
    slug: 'boston',
    displayName: 'Boston',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 42.33,
    lng: -71.07,
    aliases: ['bos'],
    wikidataId: null,
    vibes: ['scholarly', 'scrappy', 'storied'],
    svgCitiesSlug: 'us-boston',
  },
  {
    slug: 'miami',
    displayName: 'Miami',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 25.79,
    lng: -80.22,
    aliases: ['mia'],
    wikidataId: null,
    vibes: ['tropical', 'electric', 'vivid'],
    svgCitiesSlug: 'us-miami',
  },
  {
    slug: 'seattle',
    displayName: 'Seattle',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 47.57,
    lng: -122.34,
    aliases: ['sea'],
    wikidataId: null,
    vibes: ['cozy', 'caffeinated', 'misty'],
    svgCitiesSlug: 'us-seattle',
  },
  {
    slug: 'denver',
    displayName: 'Denver',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Denver',
    lat: 39.74,
    lng: -104.98,
    aliases: ['den'],
    wikidataId: null,
    vibes: ['alpine', 'outdoorsy', 'crisp'],
    svgCitiesSlug: 'us-denver',
  },
  {
    slug: 'austin',
    displayName: 'Austin',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 30.27,
    lng: -97.74,
    aliases: ['aus'],
    wikidataId: null,
    vibes: ['weird', 'creative', 'hot'],
    svgCitiesSlug: 'us-austin',
  },
  {
    slug: 'portland',
    displayName: 'Portland',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 45.52,
    lng: -122.68,
    aliases: ['pdx'],
    wikidataId: null,
    vibes: ['quirky', 'rainy', 'chill'],
    svgCitiesSlug: null,
  },
  {
    slug: 'dallas',
    displayName: 'Dallas',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 32.82,
    lng: -96.84,
    aliases: ['dfw'],
    wikidataId: null,
    vibes: ['big', 'brash', 'sprawling'],
    svgCitiesSlug: null,
  },
  {
    slug: 'houston',
    displayName: 'Houston',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 29.82,
    lng: -95.34,
    aliases: ['hou'],
    wikidataId: null,
    vibes: ['ambitious', 'sprawling', 'steamy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'atlanta',
    displayName: 'Atlanta',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 33.83,
    lng: -84.40,
    aliases: ['atl'],
    wikidataId: null,
    vibes: ['southern', 'buzzing', 'warm'],
    svgCitiesSlug: 'us-atlanta',
  },
  {
    slug: 'las-vegas',
    displayName: 'Las Vegas',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 36.21,
    lng: -115.22,
    aliases: ['vegas'],
    wikidataId: null,
    vibes: ['flashy', 'restless', 'neon'],
    svgCitiesSlug: null,
  },
  {
    slug: 'new-orleans',
    displayName: 'New Orleans',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 30.00,
    lng: -90.04,
    aliases: ['nola'],
    wikidataId: null,
    vibes: ['sultry', 'soulful', 'festive'],
    svgCitiesSlug: 'us-new-orleans',
  },
  {
    slug: 'minneapolis',
    displayName: 'Minneapolis',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 44.98,
    lng: -93.25,
    aliases: ['msp'],
    wikidataId: null,
    vibes: ['hardy', 'friendly', 'lakeside'],
    svgCitiesSlug: null,
  },
  {
    slug: 'detroit',
    displayName: 'Detroit',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Detroit',
    lat: 42.33,
    lng: -83.08,
    aliases: ['dtw'],
    wikidataId: null,
    vibes: ['resilient', 'gritty', 'reborn'],
    svgCitiesSlug: null,
  },
  {
    slug: 'philadelphia',
    displayName: 'Philadelphia',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 40.00,
    lng: -75.17,
    aliases: ['philly'],
    wikidataId: null,
    vibes: ['scrappy', 'proud', 'historic'],
    svgCitiesSlug: 'us-philadelphia',
  },
  {
    slug: 'honolulu',
    displayName: 'Honolulu',
    country: 'USA',
    countryCode: 'US',
    iana: 'Pacific/Honolulu',
    lat: 21.31,
    lng: -157.86,
    aliases: [],
    wikidataId: null,
    vibes: ['aloha', 'breezy', 'golden'],
    svgCitiesSlug: null,
  },
  {
    slug: 'washington-dc',
    displayName: 'Washington DC',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 38.90,
    lng: -77.01,
    aliases: ['dc'],
    wikidataId: null,
    vibes: ['powerful', 'polished', 'monumental'],
    svgCitiesSlug: 'us-washington',
  },
  {
    slug: 'anchorage',
    displayName: 'Anchorage',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Anchorage',
    lat: 61.22,
    lng: -149.90,
    aliases: [],
    wikidataId: null,
    vibes: ['wild', 'rugged', 'vast'],
    svgCitiesSlug: null,
  },
  {
    slug: 'toronto',
    displayName: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Toronto',
    lat: 43.70,
    lng: -79.42,
    aliases: ['canada'],
    wikidataId: null,
    vibes: ['multicultural', 'polite', 'dynamic'],
    svgCitiesSlug: 'ca-toronto',
  },
  {
    slug: 'montreal',
    displayName: 'Montreal',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Montreal',
    lat: 45.50,
    lng: -73.58,
    aliases: [],
    wikidataId: null,
    vibes: ['bilingual', 'festive', 'artsy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'vancouver',
    displayName: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Vancouver',
    lat: 49.27,
    lng: -123.12,
    aliases: [],
    wikidataId: null,
    vibes: ['scenic', 'laid-back', 'lush'],
    svgCitiesSlug: 'ca-vancouver',
  },
  {
    slug: 'mexico-city',
    displayName: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    iana: 'America/Mexico_City',
    lat: 19.44,
    lng: -99.13,
    aliases: ['cdmx', 'mexico'],
    wikidataId: null,
    vibes: ['vibrant', 'colorful', 'ancient'],
    svgCitiesSlug: null,
  },
  {
    slug: 'albuquerque',
    displayName: 'Albuquerque',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Denver',
    lat: 35.08,
    lng: -106.65,
    aliases: [],
    wikidataId: null,
    vibes: ['sun-baked', 'expansive', 'mystical'],
    svgCitiesSlug: 'us-albuquerque',
  },
  {
    slug: 'cincinnati',
    displayName: 'Cincinnati',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 39.10,
    lng: -84.51,
    aliases: [],
    wikidataId: null,
    vibes: ['unpretentious', 'steady', 'riverbound'],
    svgCitiesSlug: 'us-cincinnati',
  },
  {
    slug: 'columbus',
    displayName: 'Columbus',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 39.96,
    lng: -83.00,
    aliases: [],
    wikidataId: null,
    vibes: ['earnest', 'balanced', 'grounded'],
    svgCitiesSlug: 'us-columbus',
  },
  {
    slug: 'hartford',
    displayName: 'Hartford',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 41.76,
    lng: -72.68,
    aliases: [],
    wikidataId: null,
    vibes: ['nostalgic', 'quiet', 'weathered'],
    svgCitiesSlug: 'us-hartford',
  },
  {
    slug: 'irvine',
    displayName: 'Irvine',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 33.68,
    lng: -117.83,
    aliases: [],
    wikidataId: null,
    vibes: ['polished', 'orderly', 'pristine'],
    svgCitiesSlug: 'us-irvine',
  },
  {
    slug: 'peoria',
    displayName: 'Peoria',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 40.69,
    lng: -89.59,
    aliases: [],
    wikidataId: null,
    vibes: ['humble', 'unhurried', 'practical'],
    svgCitiesSlug: 'us-peoria',
  },
  {
    slug: 'phoenix',
    displayName: 'Phoenix',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Phoenix',
    lat: 33.45,
    lng: -112.07,
    aliases: [],
    wikidataId: null,
    vibes: ['scorched', 'resilient', 'sprawling'],
    svgCitiesSlug: 'us-phoenix',
  },
  {
    slug: 'pittsburgh',
    displayName: 'Pittsburgh',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 40.44,
    lng: -80.00,
    aliases: [],
    wikidataId: null,
    vibes: ['gritty', 'proud', 'blue-collar'],
    svgCitiesSlug: 'us-pittsburgh',
  },
  {
    slug: 'sacramento',
    displayName: 'Sacramento',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 38.58,
    lng: -121.49,
    aliases: [],
    wikidataId: null,
    vibes: ['laid-back', 'sunlit', 'easygoing'],
    svgCitiesSlug: 'us-sacramento',
  },
  {
    slug: 'san-diego',
    displayName: 'San Diego',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 32.72,
    lng: -117.16,
    aliases: [],
    wikidataId: null,
    vibes: ['breezy', 'sun-kissed', 'carefree'],
    svgCitiesSlug: 'us-san-diego',
  },
  {
    slug: 'st-louis',
    displayName: 'St. Louis',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 38.63,
    lng: -90.20,
    aliases: [],
    wikidataId: null,
    vibes: ['soulful', 'midwestern', 'unpretentious'],
    svgCitiesSlug: 'us-st-louis',
  },
  {
    slug: 'ottawa',
    displayName: 'Ottawa',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Toronto',
    lat: 45.42,
    lng: -75.70,
    aliases: [],
    wikidataId: null,
    vibes: ['dignified', 'bilingual', 'crisp'],
    svgCitiesSlug: 'ca-ottawa',
  },
  {
    slug: 'guadalajara',
    displayName: 'Guadalajara',
    country: 'Mexico',
    countryCode: 'MX',
    iana: 'America/Mexico_City',
    lat: 20.68,
    lng: -103.35,
    aliases: [],
    wikidataId: null,
    vibes: ['spirited', 'traditional', 'warm'],
    svgCitiesSlug: 'mx-guadalajara',
  },
  {
    slug: 'tijuana',
    displayName: 'Tijuana',
    country: 'Mexico',
    countryCode: 'MX',
    iana: 'America/Tijuana',
    lat: 32.52,
    lng: -117.04,
    aliases: [],
    wikidataId: null,
    vibes: ['edgy', 'border-crossing', 'hustling'],
    svgCitiesSlug: 'mx-tijuana',
  },
  {
    slug: 'san-juan',
    displayName: 'San Juan',
    country: 'Puerto Rico',
    countryCode: 'PR',
    iana: 'America/Puerto_Rico',
    lat: 18.47,
    lng: -66.11,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'salsa-ready', 'vibrant'],
    svgCitiesSlug: 'pr-san-juan',
  },

  // --- South America ---
  {
    slug: 'sao-paulo',
    displayName: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    iana: 'America/Sao_Paulo',
    lat: -23.56,
    lng: -46.63,
    aliases: ['brazil'],
    wikidataId: null,
    vibes: ['intense', 'rhythmic', 'massive'],
    svgCitiesSlug: 'br-sao-paulo',
  },
  {
    slug: 'buenos-aires',
    displayName: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    iana: 'America/Argentina/Buenos_Aires',
    lat: -34.60,
    lng: -58.40,
    aliases: ['argentina'],
    wikidataId: null,
    vibes: ['passionate', 'elegant', 'nocturnal'],
    svgCitiesSlug: 'ar-buenos-aires',
  },
  {
    slug: 'bogota',
    displayName: 'Bogota',
    country: 'Colombia',
    countryCode: 'CO',
    iana: 'America/Bogota',
    lat: 4.60,
    lng: -74.08,
    aliases: ['colombia'],
    wikidataId: null,
    vibes: ['warm', 'lively', 'elevated'],
    svgCitiesSlug: 'co-bogota',
  },
  {
    slug: 'lima',
    displayName: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    iana: 'America/Lima',
    lat: -12.05,
    lng: -77.05,
    aliases: ['peru'],
    wikidataId: null,
    vibes: ['misty', 'flavorful', 'ancient'],
    svgCitiesSlug: 'pe-lima',
  },
  {
    slug: 'santiago',
    displayName: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    iana: 'America/Santiago',
    lat: -33.45,
    lng: -70.67,
    aliases: ['chile'],
    wikidataId: null,
    vibes: ['cosmopolitan', 'crisp', 'adventurous'],
    svgCitiesSlug: 'cl-santiago',
  },
  {
    slug: 'cordoba-argentina',
    displayName: 'Cordoba',
    country: 'Argentina',
    countryCode: 'AR',
    iana: 'America/Argentina/Cordoba',
    lat: -31.42,
    lng: -64.18,
    aliases: [],
    wikidataId: null,
    vibes: ['scholarly', 'passionate', 'rebellious'],
    svgCitiesSlug: 'ar-cordoba',
  },
  {
    slug: 'ushuaia',
    displayName: 'Ushuaia',
    country: 'Argentina',
    countryCode: 'AR',
    iana: 'America/Argentina/Ushuaia',
    lat: -54.81,
    lng: -68.31,
    aliases: [],
    wikidataId: null,
    vibes: ['windswept', 'remote', 'adventurous'],
    svgCitiesSlug: 'ar-ushuaia',
  },
  {
    slug: 'la-paz',
    displayName: 'La Paz',
    country: 'Bolivia',
    countryCode: 'BO',
    iana: 'America/La_Paz',
    lat: -16.50,
    lng: -68.15,
    aliases: [],
    wikidataId: null,
    vibes: ['breathless', 'high-altitude', 'dizzying'],
    svgCitiesSlug: 'bo-la-paz',
  },
  {
    slug: 'brasilia',
    displayName: 'Brasilia',
    country: 'Brazil',
    countryCode: 'BR',
    iana: 'America/Sao_Paulo',
    lat: -15.79,
    lng: -47.88,
    aliases: [],
    wikidataId: null,
    vibes: ['modernist', 'planned', 'spacious'],
    svgCitiesSlug: 'br-brasilia',
  },
  {
    slug: 'rio-de-janeiro',
    displayName: 'Rio de Janeiro',
    country: 'Brazil',
    countryCode: 'BR',
    iana: 'America/Sao_Paulo',
    lat: -22.91,
    lng: -43.17,
    aliases: [],
    wikidataId: null,
    vibes: ['sensual', 'exuberant', 'sun-drenched'],
    svgCitiesSlug: 'br-rio-de-janeiro',
  },
  {
    slug: 'valparaiso',
    displayName: 'Valparaiso',
    country: 'Chile',
    countryCode: 'CL',
    iana: 'America/Santiago',
    lat: -33.05,
    lng: -71.62,
    aliases: [],
    wikidataId: null,
    vibes: ['bohemian', 'colorful', 'hilly'],
    svgCitiesSlug: 'cl-valparaiso',
  },
  {
    slug: 'cartagena',
    displayName: 'Cartagena',
    country: 'Colombia',
    countryCode: 'CO',
    iana: 'America/Bogota',
    lat: 10.39,
    lng: -75.51,
    aliases: [],
    wikidataId: null,
    vibes: ['sultry', 'colonial', 'festive'],
    svgCitiesSlug: 'co-cartagena',
  },
  {
    slug: 'medellin',
    displayName: 'Medellin',
    country: 'Colombia',
    countryCode: 'CO',
    iana: 'America/Bogota',
    lat: 6.25,
    lng: -75.57,
    aliases: [],
    wikidataId: null,
    vibes: ['transformed', 'innovative', 'springlike'],
    svgCitiesSlug: 'co-medellin',
  },
  {
    slug: 'quito',
    displayName: 'Quito',
    country: 'Ecuador',
    countryCode: 'EC',
    iana: 'America/Guayaquil',
    lat: -0.18,
    lng: -78.47,
    aliases: [],
    wikidataId: null,
    vibes: ['elevated', 'colonial', 'crisp'],
    svgCitiesSlug: 'ec-quito',
  },
  {
    slug: 'cusco',
    displayName: 'Cusco',
    country: 'Peru',
    countryCode: 'PE',
    iana: 'America/Lima',
    lat: -13.52,
    lng: -71.97,
    aliases: [],
    wikidataId: null,
    vibes: ['ancient', 'mystical', 'thin-aired'],
    svgCitiesSlug: 'pe-cusco',
  },
  {
    slug: 'montevideo',
    displayName: 'Montevideo',
    country: 'Uruguay',
    countryCode: 'UY',
    iana: 'America/Montevideo',
    lat: -34.88,
    lng: -56.17,
    aliases: [],
    wikidataId: null,
    vibes: ['relaxed', 'literary', 'coastal'],
    svgCitiesSlug: 'uy-montevideo',
  },
  {
    slug: 'caracas',
    displayName: 'Caracas',
    country: 'Venezuela',
    countryCode: 'VE',
    iana: 'America/Caracas',
    lat: 10.49,
    lng: -66.88,
    aliases: [],
    wikidataId: null,
    vibes: ['intense', 'volatile', 'mountainous'],
    svgCitiesSlug: 've-caracas',
  },

  // --- Europe ---
  {
    slug: 'london',
    displayName: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 51.50,
    lng: -0.12,
    aliases: ['uk', 'england'],
    wikidataId: null,
    vibes: ['posh', 'cozy', 'literary'],
    svgCitiesSlug: 'gb-london',
  },
  {
    slug: 'paris',
    displayName: 'Paris',
    country: 'France',
    countryCode: 'FR',
    iana: 'Europe/Paris',
    lat: 48.87,
    lng: 2.33,
    aliases: ['france'],
    wikidataId: null,
    vibes: ['romantic', 'chic', 'dreamy'],
    svgCitiesSlug: 'fr-paris',
  },
  {
    slug: 'berlin',
    displayName: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 52.52,
    lng: 13.40,
    aliases: ['germany'],
    wikidataId: null,
    vibes: ['free', 'underground', 'raw'],
    svgCitiesSlug: 'de-berlin',
  },
  {
    slug: 'zurich',
    displayName: 'Zurich',
    country: 'Switzerland',
    countryCode: 'CH',
    iana: 'Europe/Zurich',
    lat: 47.38,
    lng: 8.55,
    aliases: ['switzerland'],
    wikidataId: null,
    vibes: ['precise', 'pristine', 'alpine'],
    svgCitiesSlug: null,
  },
  {
    slug: 'amsterdam',
    displayName: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    iana: 'Europe/Amsterdam',
    lat: 52.35,
    lng: 4.92,
    aliases: ['netherlands', 'holland'],
    wikidataId: null,
    vibes: ['open-minded', 'breezy', 'candid'],
    svgCitiesSlug: 'nl-amsterdam',
  },
  {
    slug: 'rome',
    displayName: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 41.90,
    lng: 12.48,
    aliases: ['italy'],
    wikidataId: null,
    vibes: ['eternal', 'warm', 'dramatic'],
    svgCitiesSlug: 'it-rome',
  },
  {
    slug: 'madrid',
    displayName: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 40.40,
    lng: -3.68,
    aliases: ['spain'],
    wikidataId: null,
    vibes: ['fiery', 'nocturnal', 'proud'],
    svgCitiesSlug: 'es-madrid',
  },
  {
    slug: 'lisbon',
    displayName: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 38.72,
    lng: -9.14,
    aliases: ['portugal'],
    wikidataId: null,
    vibes: ['melancholic', 'sunny', 'soulful'],
    svgCitiesSlug: 'pt-lisbon',
  },
  {
    slug: 'stockholm',
    displayName: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    iana: 'Europe/Stockholm',
    lat: 59.35,
    lng: 18.10,
    aliases: ['sweden'],
    wikidataId: null,
    vibes: ['minimal', 'sleek', 'thoughtful'],
    svgCitiesSlug: 'se-stockholm',
  },
  {
    slug: 'oslo',
    displayName: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    iana: 'Europe/Oslo',
    lat: 59.92,
    lng: 10.75,
    aliases: ['norway'],
    wikidataId: null,
    vibes: ['rugged', 'quiet', 'pristine'],
    svgCitiesSlug: 'no-oslo',
  },
  {
    slug: 'copenhagen',
    displayName: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    iana: 'Europe/Copenhagen',
    lat: 55.68,
    lng: 12.57,
    aliases: ['denmark'],
    wikidataId: null,
    vibes: ['hygge', 'cozy', 'whimsical'],
    svgCitiesSlug: 'dk-copenhagen',
  },
  {
    slug: 'helsinki',
    displayName: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    iana: 'Europe/Helsinki',
    lat: 60.18,
    lng: 24.93,
    aliases: ['finland'],
    wikidataId: null,
    vibes: ['stoic', 'serene', 'luminous'],
    svgCitiesSlug: 'fi-helsinki',
  },
  {
    slug: 'vienna',
    displayName: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    iana: 'Europe/Vienna',
    lat: 48.20,
    lng: 16.37,
    aliases: ['austria'],
    wikidataId: null,
    vibes: ['refined', 'classical', 'grand'],
    svgCitiesSlug: 'at-vienna',
  },
  {
    slug: 'brussels',
    displayName: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    iana: 'Europe/Brussels',
    lat: 50.83,
    lng: 4.33,
    aliases: ['belgium'],
    wikidataId: null,
    vibes: ['cosmopolitan', 'quirky', 'indulgent'],
    svgCitiesSlug: 'be-brussels',
  },
  {
    slug: 'warsaw',
    displayName: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    iana: 'Europe/Warsaw',
    lat: 52.25,
    lng: 21.00,
    aliases: ['poland'],
    wikidataId: null,
    vibes: ['resilient', 'rising', 'spirited'],
    svgCitiesSlug: 'pl-warsaw',
  },
  {
    slug: 'prague',
    displayName: 'Prague',
    country: 'Czech Republic',
    countryCode: 'CZ',
    iana: 'Europe/Prague',
    lat: 50.08,
    lng: 14.47,
    aliases: ['czech republic', 'czechia'],
    wikidataId: null,
    vibes: ['bohemian', 'golden', 'enchanted'],
    svgCitiesSlug: 'cz-prague',
  },
  {
    slug: 'athens',
    displayName: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    iana: 'Europe/Athens',
    lat: 37.98,
    lng: 23.73,
    aliases: ['greece'],
    wikidataId: null,
    vibes: ['ancient', 'sun-drenched', 'philosophical'],
    svgCitiesSlug: 'gr-athens',
  },
  {
    slug: 'istanbul',
    displayName: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    iana: 'Europe/Istanbul',
    lat: 41.10,
    lng: 29.01,
    aliases: ['turkey'],
    wikidataId: null,
    vibes: ['mystical', 'bustling', 'layered'],
    svgCitiesSlug: 'tr-istanbul',
  },
  {
    slug: 'moscow',
    displayName: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    iana: 'Europe/Moscow',
    lat: 55.75,
    lng: 37.62,
    aliases: ['russia'],
    wikidataId: null,
    vibes: ['imposing', 'wintry', 'grand'],
    svgCitiesSlug: 'ru-moscow',
  },
  {
    slug: 'dublin',
    displayName: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    iana: 'Europe/Dublin',
    lat: 53.33,
    lng: -6.25,
    aliases: ['ireland'],
    wikidataId: null,
    vibes: ['convivial', 'witty', 'rainy'],
    svgCitiesSlug: 'ie-dublin',
  },
  {
    slug: 'edinburgh',
    displayName: 'Edinburgh',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 55.95,
    lng: -3.22,
    aliases: ['scotland'],
    wikidataId: null,
    vibes: ['moody', 'storied', 'misty'],
    svgCitiesSlug: 'gb-edinburgh',
  },
  {
    slug: 'reykjavik',
    displayName: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    iana: 'Atlantic/Reykjavik',
    lat: 64.15,
    lng: -21.95,
    aliases: [],
    wikidataId: null,
    vibes: ['otherworldly', 'stark', 'luminous'],
    svgCitiesSlug: 'is-reykjavik',
  },
  {
    slug: 'andorra-la-vella',
    displayName: 'Andorra la Vella',
    country: 'Andorra',
    countryCode: 'AD',
    iana: 'Europe/Andorra',
    lat: 42.51,
    lng: 1.52,
    aliases: [],
    wikidataId: null,
    vibes: ['alpine', 'duty-free', 'tucked-away'],
    svgCitiesSlug: 'ad-andorra',
  },
  {
    slug: 'tirana',
    displayName: 'Tirana',
    country: 'Albania',
    countryCode: 'AL',
    iana: 'Europe/Tirane',
    lat: 41.33,
    lng: 19.82,
    aliases: [],
    wikidataId: null,
    vibes: ['colorful', 'scrappy', 'emerging'],
    svgCitiesSlug: 'al-tirana',
  },
  {
    slug: 'baku',
    displayName: 'Baku',
    country: 'Azerbaijan',
    countryCode: 'AZ',
    iana: 'Asia/Baku',
    lat: 40.41,
    lng: 49.87,
    aliases: [],
    wikidataId: null,
    vibes: ['windy', 'oil-slicked', 'cosmopolitan'],
    svgCitiesSlug: 'az-baku',
  },
  {
    slug: 'mostar',
    displayName: 'Mostar',
    country: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    iana: 'Europe/Sarajevo',
    lat: 43.34,
    lng: 17.81,
    aliases: [],
    wikidataId: null,
    vibes: ['bridged', 'resilient', 'haunted'],
    svgCitiesSlug: 'ba-mostar',
  },
  {
    slug: 'sarajevo',
    displayName: 'Sarajevo',
    country: 'Bosnia and Herzegovina',
    countryCode: 'BA',
    iana: 'Europe/Sarajevo',
    lat: 43.86,
    lng: 18.41,
    aliases: [],
    wikidataId: null,
    vibes: ['scarred', 'multicultural', 'spirited'],
    svgCitiesSlug: 'ba-sarajevo',
  },
  {
    slug: 'bruges',
    displayName: 'Bruges',
    country: 'Belgium',
    countryCode: 'BE',
    iana: 'Europe/Brussels',
    lat: 51.21,
    lng: 3.22,
    aliases: [],
    wikidataId: null,
    vibes: ['medieval', 'tranquil', 'chocolatey'],
    svgCitiesSlug: 'be-bruges',
  },
  {
    slug: 'sofia',
    displayName: 'Sofia',
    country: 'Bulgaria',
    countryCode: 'BG',
    iana: 'Europe/Sofia',
    lat: 42.70,
    lng: 23.32,
    aliases: [],
    wikidataId: null,
    vibes: ['post-soviet', 'leafy', 'unpolished'],
    svgCitiesSlug: 'bg-sofia',
  },
  {
    slug: 'minsk',
    displayName: 'Minsk',
    country: 'Belarus',
    countryCode: 'BY',
    iana: 'Europe/Minsk',
    lat: 53.90,
    lng: 27.57,
    aliases: [],
    wikidataId: null,
    vibes: ['soviet-era', 'orderly', 'melancholic'],
    svgCitiesSlug: 'by-minsk',
  },
  {
    slug: 'bern',
    displayName: 'Bern',
    country: 'Switzerland',
    countryCode: 'CH',
    iana: 'Europe/Zurich',
    lat: 46.95,
    lng: 7.45,
    aliases: [],
    wikidataId: null,
    vibes: ['calm', 'arcaded', 'genteel'],
    svgCitiesSlug: 'ch-bern',
  },
  {
    slug: 'limassol',
    displayName: 'Limassol',
    country: 'Cyprus',
    countryCode: 'CY',
    iana: 'Asia/Nicosia',
    lat: 34.68,
    lng: 33.04,
    aliases: [],
    wikidataId: null,
    vibes: ['sunny', 'beachfront', 'relaxed'],
    svgCitiesSlug: 'cy-limassol',
  },
  {
    slug: 'nicosia',
    displayName: 'Nicosia',
    country: 'Cyprus',
    countryCode: 'CY',
    iana: 'Asia/Nicosia',
    lat: 35.17,
    lng: 33.37,
    aliases: [],
    wikidataId: null,
    vibes: ['divided', 'warm', 'liminal'],
    svgCitiesSlug: 'cy-nicosia',
  },
  {
    slug: 'paphos',
    displayName: 'Paphos',
    country: 'Cyprus',
    countryCode: 'CY',
    iana: 'Asia/Nicosia',
    lat: 34.78,
    lng: 32.42,
    aliases: [],
    wikidataId: null,
    vibes: ['mythical', 'seaside', 'languid'],
    svgCitiesSlug: 'cy-paphos',
  },
  {
    slug: 'aachen',
    displayName: 'Aachen',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 50.78,
    lng: 6.08,
    aliases: [],
    wikidataId: null,
    vibes: ['thermal', 'imperial', 'cross-border'],
    svgCitiesSlug: 'de-aachen',
  },
  {
    slug: 'bielefeld',
    displayName: 'Bielefeld',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 52.02,
    lng: 8.53,
    aliases: [],
    wikidataId: null,
    vibes: ['unassuming', 'industrial', 'modest'],
    svgCitiesSlug: 'de-bielefeld',
  },
  {
    slug: 'bremen',
    displayName: 'Bremen',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 53.08,
    lng: 8.80,
    aliases: [],
    wikidataId: null,
    vibes: ['maritime', 'hanseatic', 'independent'],
    svgCitiesSlug: 'de-bremen',
  },
  {
    slug: 'cologne',
    displayName: 'Cologne',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 50.94,
    lng: 6.96,
    aliases: [],
    wikidataId: null,
    vibes: ['carnival-ready', 'jovial', 'cathedral-shadowed'],
    svgCitiesSlug: 'de-cologne',
  },
  {
    slug: 'erfurt',
    displayName: 'Erfurt',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 50.98,
    lng: 11.03,
    aliases: [],
    wikidataId: null,
    vibes: ['floral', 'medieval', 'gentle'],
    svgCitiesSlug: 'de-erfurt',
  },
  {
    slug: 'frankfurt',
    displayName: 'Frankfurt',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 50.11,
    lng: 8.68,
    aliases: [],
    wikidataId: null,
    vibes: ['financial', 'transient', 'glass-towered'],
    svgCitiesSlug: 'de-frankfurt',
  },
  {
    slug: 'freiburg',
    displayName: 'Freiburg',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 47.99,
    lng: 7.85,
    aliases: [],
    wikidataId: null,
    vibes: ['sunny', 'eco-conscious', 'youthful'],
    svgCitiesSlug: 'de-freiburg',
  },
  {
    slug: 'giessen',
    displayName: 'Giessen',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 50.58,
    lng: 8.68,
    aliases: [],
    wikidataId: null,
    vibes: ['studious', 'small-town', 'unpretentious'],
    svgCitiesSlug: 'de-giessen',
  },
  {
    slug: 'hamburg',
    displayName: 'Hamburg',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 53.55,
    lng: 9.99,
    aliases: [],
    wikidataId: null,
    vibes: ['maritime', 'liberal', 'rainy'],
    svgCitiesSlug: 'de-hamburg',
  },
  {
    slug: 'karlsruhe',
    displayName: 'Karlsruhe',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 49.01,
    lng: 8.40,
    aliases: [],
    wikidataId: null,
    vibes: ['planned', 'sunny', 'cultured'],
    svgCitiesSlug: 'de-karlsruhe',
  },
  {
    slug: 'leipzig',
    displayName: 'Leipzig',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 51.34,
    lng: 12.37,
    aliases: [],
    wikidataId: null,
    vibes: ['artistic', 'rebellious', 'emerging'],
    svgCitiesSlug: 'de-leipzig',
  },
  {
    slug: 'munich',
    displayName: 'Munich',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 48.14,
    lng: 11.58,
    aliases: [],
    wikidataId: null,
    vibes: ['gemutlich', 'beer-garden-ready', 'prosperous'],
    svgCitiesSlug: 'de-munich',
  },
  {
    slug: 'nuremberg',
    displayName: 'Nuremberg',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 49.45,
    lng: 11.08,
    aliases: [],
    wikidataId: null,
    vibes: ['medieval', 'contemplative', 'historic'],
    svgCitiesSlug: 'de-nuremberg',
  },
  {
    slug: 'siegen',
    displayName: 'Siegen',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 50.87,
    lng: 8.02,
    aliases: [],
    wikidataId: null,
    vibes: ['forested', 'hilly', 'tucked-away'],
    svgCitiesSlug: 'de-siegen',
  },
  {
    slug: 'stuttgart',
    displayName: 'Stuttgart',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 48.78,
    lng: 9.18,
    aliases: [],
    wikidataId: null,
    vibes: ['engineered', 'industrious', 'hilly'],
    svgCitiesSlug: 'de-stuttgart',
  },
  {
    slug: 'tallinn',
    displayName: 'Tallinn',
    country: 'Estonia',
    countryCode: 'EE',
    iana: 'Europe/Tallinn',
    lat: 59.44,
    lng: 24.75,
    aliases: [],
    wikidataId: null,
    vibes: ['medieval', 'digital', 'baltic'],
    svgCitiesSlug: 'ee-tallinn',
  },
  {
    slug: 'barcelona',
    displayName: 'Barcelona',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 41.39,
    lng: 2.17,
    aliases: [],
    wikidataId: null,
    vibes: ['sensual', 'modernist', 'rebellious'],
    svgCitiesSlug: 'es-barcelona',
  },
  {
    slug: 'cordoba-spain',
    displayName: 'Cordoba',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 37.88,
    lng: -4.78,
    aliases: [],
    wikidataId: null,
    vibes: ['moorish', 'scorching', 'contemplative'],
    svgCitiesSlug: 'es-cordoba',
  },
  {
    slug: 'a-coruna',
    displayName: 'A Coruna',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 43.37,
    lng: -8.40,
    aliases: [],
    wikidataId: null,
    vibes: ['windswept', 'maritime', 'galician'],
    svgCitiesSlug: 'es-coruna',
  },
  {
    slug: 'gijon',
    displayName: 'Gijon',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 43.54,
    lng: -5.66,
    aliases: [],
    wikidataId: null,
    vibes: ['salty', 'working-class', 'green'],
    svgCitiesSlug: 'es-gijon',
  },
  {
    slug: 'granada-spain',
    displayName: 'Granada',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 37.18,
    lng: -3.60,
    aliases: [],
    wikidataId: null,
    vibes: ['moorish', 'poetic', 'twilit'],
    svgCitiesSlug: 'es-granada',
  },
  {
    slug: 'malaga',
    displayName: 'Malaga',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 36.72,
    lng: -4.42,
    aliases: [],
    wikidataId: null,
    vibes: ['sun-soaked', 'coastal', 'breezy'],
    svgCitiesSlug: 'es-malaga',
  },
  {
    slug: 'santiago-de-compostela',
    displayName: 'Santiago de Compostela',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 42.88,
    lng: -8.54,
    aliases: [],
    wikidataId: null,
    vibes: ['pilgrim-weary', 'sacred', 'misty'],
    svgCitiesSlug: 'es-santiago-de-compostela',
  },
  {
    slug: 'valencia',
    displayName: 'Valencia',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 39.47,
    lng: -0.38,
    aliases: [],
    wikidataId: null,
    vibes: ['sunlit', 'orange-scented', 'modern'],
    svgCitiesSlug: 'es-valencia',
  },
  {
    slug: 'vigo',
    displayName: 'Vigo',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 42.23,
    lng: -8.72,
    aliases: [],
    wikidataId: null,
    vibes: ['rainy', 'maritime', 'industrial'],
    svgCitiesSlug: 'es-vigo',
  },
  {
    slug: 'kuopio',
    displayName: 'Kuopio',
    country: 'Finland',
    countryCode: 'FI',
    iana: 'Europe/Helsinki',
    lat: 62.89,
    lng: 27.68,
    aliases: [],
    wikidataId: null,
    vibes: ['lakeside', 'sauna-ready', 'tranquil'],
    svgCitiesSlug: 'fi-kuopio',
  },
  {
    slug: 'lyon',
    displayName: 'Lyon',
    country: 'France',
    countryCode: 'FR',
    iana: 'Europe/Paris',
    lat: 45.76,
    lng: 4.83,
    aliases: [],
    wikidataId: null,
    vibes: ['gastronomic', 'silky', 'traboule-hidden'],
    svgCitiesSlug: 'fr-lyon',
  },
  {
    slug: 'montpellier',
    displayName: 'Montpellier',
    country: 'France',
    countryCode: 'FR',
    iana: 'Europe/Paris',
    lat: 43.61,
    lng: 3.88,
    aliases: [],
    wikidataId: null,
    vibes: ['sunny', 'youthful', 'mediterranean'],
    svgCitiesSlug: 'fr-montpellier',
  },
  {
    slug: 'rennes',
    displayName: 'Rennes',
    country: 'France',
    countryCode: 'FR',
    iana: 'Europe/Paris',
    lat: 48.11,
    lng: -1.68,
    aliases: [],
    wikidataId: null,
    vibes: ['rainy', 'breton', 'studious'],
    svgCitiesSlug: 'fr-rennes',
  },
  {
    slug: 'leeds',
    displayName: 'Leeds',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 53.80,
    lng: -1.55,
    aliases: [],
    wikidataId: null,
    vibes: ['post-industrial', 'direct', 'northern'],
    svgCitiesSlug: 'gb-leeds',
  },
  {
    slug: 'manchester',
    displayName: 'Manchester',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 53.48,
    lng: -2.24,
    aliases: [],
    wikidataId: null,
    vibes: ['rainy', 'musical', 'gritty'],
    svgCitiesSlug: 'gb-manchester',
  },
  {
    slug: 'batumi',
    displayName: 'Batumi',
    country: 'Georgia',
    countryCode: 'GE',
    iana: 'Asia/Tbilisi',
    lat: 41.64,
    lng: 41.63,
    aliases: [],
    wikidataId: null,
    vibes: ['subtropical', 'casino-lit', 'humid'],
    svgCitiesSlug: 'ge-batumi',
  },
  {
    slug: 'tbilisi',
    displayName: 'Tbilisi',
    country: 'Georgia',
    countryCode: 'GE',
    iana: 'Asia/Tbilisi',
    lat: 41.69,
    lng: 44.80,
    aliases: [],
    wikidataId: null,
    vibes: ['sulfuric', 'bohemian', 'crossroads'],
    svgCitiesSlug: 'ge-tbilisi',
  },
  {
    slug: 'zagreb',
    displayName: 'Zagreb',
    country: 'Croatia',
    countryCode: 'HR',
    iana: 'Europe/Zagreb',
    lat: 45.81,
    lng: 15.98,
    aliases: [],
    wikidataId: null,
    vibes: ['cafe-lingering', 'post-yugoslav', 'green'],
    svgCitiesSlug: 'hr-zagreb',
  },
  {
    slug: 'budapest',
    displayName: 'Budapest',
    country: 'Hungary',
    countryCode: 'HU',
    iana: 'Europe/Budapest',
    lat: 47.50,
    lng: 19.04,
    aliases: [],
    wikidataId: null,
    vibes: ['thermal', 'melancholic', 'grand'],
    svgCitiesSlug: 'hu-budapest',
  },
  {
    slug: 'debrecen',
    displayName: 'Debrecen',
    country: 'Hungary',
    countryCode: 'HU',
    iana: 'Europe/Budapest',
    lat: 47.53,
    lng: 21.63,
    aliases: [],
    wikidataId: null,
    vibes: ['earnest', 'reformed', 'provincial'],
    svgCitiesSlug: 'hu-debrecen',
  },
  {
    slug: 'szeged',
    displayName: 'Szeged',
    country: 'Hungary',
    countryCode: 'HU',
    iana: 'Europe/Budapest',
    lat: 46.25,
    lng: 20.15,
    aliases: [],
    wikidataId: null,
    vibes: ['sunny', 'paprika-scented', 'peaceful'],
    svgCitiesSlug: 'hu-szeged',
  },
  {
    slug: 'akureyri',
    displayName: 'Akureyri',
    country: 'Iceland',
    countryCode: 'IS',
    iana: 'Atlantic/Reykjavik',
    lat: 65.68,
    lng: -18.09,
    aliases: [],
    wikidataId: null,
    vibes: ['northern', 'stark', 'cozy'],
    svgCitiesSlug: 'is-akureyri',
  },
  {
    slug: 'bologna',
    displayName: 'Bologna',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 44.49,
    lng: 11.34,
    aliases: [],
    wikidataId: null,
    vibes: ['studious', 'porticoed', 'leftist'],
    svgCitiesSlug: 'it-bologna',
  },
  {
    slug: 'ferrara',
    displayName: 'Ferrara',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 44.84,
    lng: 11.62,
    aliases: [],
    wikidataId: null,
    vibes: ['cycling', 'renaissance', 'quiet'],
    svgCitiesSlug: 'it-ferrara',
  },
  {
    slug: 'forte-dei-marmi',
    displayName: 'Forte dei Marmi',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 43.96,
    lng: 10.17,
    aliases: [],
    wikidataId: null,
    vibes: ['jet-set', 'beachside', 'exclusive'],
    svgCitiesSlug: 'it-forte-dei-marmi',
  },
  {
    slug: 'milan',
    displayName: 'Milan',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 45.46,
    lng: 9.19,
    aliases: [],
    wikidataId: null,
    vibes: ['fashionable', 'ambitious', 'sleek'],
    svgCitiesSlug: 'it-milan',
  },
  {
    slug: 'palermo',
    displayName: 'Palermo',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 38.11,
    lng: 13.35,
    aliases: [],
    wikidataId: null,
    vibes: ['chaotic', 'spicy', 'sun-beaten'],
    svgCitiesSlug: 'it-palermo',
  },
  {
    slug: 'sorrento',
    displayName: 'Sorrento',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 40.63,
    lng: 14.37,
    aliases: [],
    wikidataId: null,
    vibes: ['limoncello-sweet', 'cliffside', 'romantic'],
    svgCitiesSlug: 'it-sorrento',
  },
  {
    slug: 'taranto',
    displayName: 'Taranto',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 40.47,
    lng: 17.24,
    aliases: [],
    wikidataId: null,
    vibes: ['maritime', 'industrial', 'salty'],
    svgCitiesSlug: 'it-taranto',
  },
  {
    slug: 'trieste',
    displayName: 'Trieste',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 45.65,
    lng: 13.78,
    aliases: [],
    wikidataId: null,
    vibes: ['mitteleuropean', 'melancholic', 'coffee-scented'],
    svgCitiesSlug: 'it-trieste',
  },
  {
    slug: 'venice',
    displayName: 'Venice',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 45.44,
    lng: 12.32,
    aliases: [],
    wikidataId: null,
    vibes: ['labyrinthine', 'sinking', 'dreamlike'],
    svgCitiesSlug: 'it-venice',
  },
  {
    slug: 'vaduz',
    displayName: 'Vaduz',
    country: 'Liechtenstein',
    countryCode: 'LI',
    iana: 'Europe/Vaduz',
    lat: 47.14,
    lng: 9.52,
    aliases: [],
    wikidataId: null,
    vibes: ['alpine', 'tax-sheltered', 'tiny'],
    svgCitiesSlug: 'li-vaduz',
  },
  {
    slug: 'vilnius',
    displayName: 'Vilnius',
    country: 'Lithuania',
    countryCode: 'LT',
    iana: 'Europe/Vilnius',
    lat: 54.69,
    lng: 25.28,
    aliases: [],
    wikidataId: null,
    vibes: ['baroque', 'bohemian', 'resilient'],
    svgCitiesSlug: 'lt-vilnius',
  },
  {
    slug: 'luxembourg-city',
    displayName: 'Luxembourg City',
    country: 'Luxembourg',
    countryCode: 'LU',
    iana: 'Europe/Luxembourg',
    lat: 49.61,
    lng: 6.13,
    aliases: [],
    wikidataId: null,
    vibes: ['multilingual', 'prosperous', 'compact'],
    svgCitiesSlug: 'lu-luxembourg',
  },
  {
    slug: 'riga',
    displayName: 'Riga',
    country: 'Latvia',
    countryCode: 'LV',
    iana: 'Europe/Riga',
    lat: 56.95,
    lng: 24.11,
    aliases: [],
    wikidataId: null,
    vibes: ['art-nouveau', 'amber-lit', 'baltic'],
    svgCitiesSlug: 'lv-riga',
  },
  {
    slug: 'monaco',
    displayName: 'Monaco',
    country: 'Monaco',
    countryCode: 'MC',
    iana: 'Europe/Monaco',
    lat: 43.73,
    lng: 7.42,
    aliases: [],
    wikidataId: null,
    vibes: ['glamorous', 'tax-free', 'exclusive'],
    svgCitiesSlug: 'mc-monaco',
  },
  {
    slug: 'chisinau',
    displayName: 'Chisinau',
    country: 'Moldova',
    countryCode: 'MD',
    iana: 'Europe/Chisinau',
    lat: 47.01,
    lng: 28.86,
    aliases: [],
    wikidataId: null,
    vibes: ['post-soviet', 'quiet', 'wine-soaked'],
    svgCitiesSlug: 'md-chisinau',
  },
  {
    slug: 'budva',
    displayName: 'Budva',
    country: 'Montenegro',
    countryCode: 'ME',
    iana: 'Europe/Podgorica',
    lat: 42.29,
    lng: 18.84,
    aliases: [],
    wikidataId: null,
    vibes: ['beach-ready', 'nightlife-charged', 'adriatic'],
    svgCitiesSlug: 'me-budva',
  },
  {
    slug: 'herceg-novi',
    displayName: 'Herceg Novi',
    country: 'Montenegro',
    countryCode: 'ME',
    iana: 'Europe/Podgorica',
    lat: 42.45,
    lng: 18.54,
    aliases: [],
    wikidataId: null,
    vibes: ['floral', 'sunny', 'coastal'],
    svgCitiesSlug: 'me-herceg-novi',
  },
  {
    slug: 'podgorica',
    displayName: 'Podgorica',
    country: 'Montenegro',
    countryCode: 'ME',
    iana: 'Europe/Podgorica',
    lat: 42.44,
    lng: 19.26,
    aliases: [],
    wikidataId: null,
    vibes: ['concrete', 'functional', 'sunny'],
    svgCitiesSlug: 'me-podgorica',
  },
  {
    slug: 'skopje',
    displayName: 'Skopje',
    country: 'North Macedonia',
    countryCode: 'MK',
    iana: 'Europe/Skopje',
    lat: 41.99,
    lng: 21.43,
    aliases: [],
    wikidataId: null,
    vibes: ['rebuilt', 'eclectic', 'rough-edged'],
    svgCitiesSlug: 'mk-skopje',
  },
  {
    slug: 'valletta',
    displayName: 'Valletta',
    country: 'Malta',
    countryCode: 'MT',
    iana: 'Europe/Malta',
    lat: 35.90,
    lng: 14.51,
    aliases: [],
    wikidataId: null,
    vibes: ['honey-stoned', 'fortified', 'sunlit'],
    svgCitiesSlug: 'mt-valletta',
  },
  {
    slug: 'de-meije',
    displayName: 'De Meije',
    country: 'Netherlands',
    countryCode: 'NL',
    iana: 'Europe/Amsterdam',
    lat: 52.08,
    lng: 4.84,
    aliases: [],
    wikidataId: null,
    vibes: ['pastoral', 'watery', 'tranquil'],
    svgCitiesSlug: 'nl-de-meije',
  },
  {
    slug: 'maastricht',
    displayName: 'Maastricht',
    country: 'Netherlands',
    countryCode: 'NL',
    iana: 'Europe/Amsterdam',
    lat: 50.85,
    lng: 5.69,
    aliases: [],
    wikidataId: null,
    vibes: ['hilly', 'border-crossing', 'burgundian'],
    svgCitiesSlug: 'nl-maastricht',
  },
  {
    slug: 'rotterdam',
    displayName: 'Rotterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    iana: 'Europe/Amsterdam',
    lat: 51.92,
    lng: 4.48,
    aliases: [],
    wikidataId: null,
    vibes: ['rebuilt', 'bold', 'architectural'],
    svgCitiesSlug: 'nl-rotterdam',
  },
  {
    slug: 'woerden',
    displayName: 'Woerden',
    country: 'Netherlands',
    countryCode: 'NL',
    iana: 'Europe/Amsterdam',
    lat: 52.09,
    lng: 4.88,
    aliases: [],
    wikidataId: null,
    vibes: ['canal-lined', 'cheese-market-fresh', 'quiet'],
    svgCitiesSlug: 'nl-woerden',
  },
  {
    slug: 'gdansk',
    displayName: 'Gdansk',
    country: 'Poland',
    countryCode: 'PL',
    iana: 'Europe/Warsaw',
    lat: 54.35,
    lng: 18.65,
    aliases: [],
    wikidataId: null,
    vibes: ['hanseatic', 'amber-tinged', 'maritime'],
    svgCitiesSlug: 'pl-gdansk',
  },
  {
    slug: 'poznan',
    displayName: 'Poznan',
    country: 'Poland',
    countryCode: 'PL',
    iana: 'Europe/Warsaw',
    lat: 52.41,
    lng: 16.93,
    aliases: [],
    wikidataId: null,
    vibes: ['mercantile', 'colorful', 'proud'],
    svgCitiesSlug: 'pl-poznan',
  },
  {
    slug: 'swiebodzin',
    displayName: 'Swiebodzin',
    country: 'Poland',
    countryCode: 'PL',
    iana: 'Europe/Warsaw',
    lat: 52.25,
    lng: 15.53,
    aliases: [],
    wikidataId: null,
    vibes: ['small-town', 'quiet', 'faithful'],
    svgCitiesSlug: 'pl-swiebodzin',
  },
  {
    slug: 'wroclaw',
    displayName: 'Wroclaw',
    country: 'Poland',
    countryCode: 'PL',
    iana: 'Europe/Warsaw',
    lat: 51.11,
    lng: 17.04,
    aliases: [],
    wikidataId: null,
    vibes: ['island-dotted', 'gnome-spotted', 'colorful'],
    svgCitiesSlug: 'pl-wroclaw',
  },
  {
    slug: 'amadora',
    displayName: 'Amadora',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 38.75,
    lng: -9.24,
    aliases: [],
    wikidataId: null,
    vibes: ['residential', 'unpretentious', 'suburban'],
    svgCitiesSlug: 'pt-amadora',
  },
  {
    slug: 'barcelos',
    displayName: 'Barcelos',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.53,
    lng: -8.62,
    aliases: [],
    wikidataId: null,
    vibes: ['folkloric', 'ceramic', 'traditional'],
    svgCitiesSlug: 'pt-barcelos',
  },
  {
    slug: 'braga',
    displayName: 'Braga',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.55,
    lng: -8.43,
    aliases: [],
    wikidataId: null,
    vibes: ['baroque', 'youthful', 'faithful'],
    svgCitiesSlug: 'pt-braga',
  },
  {
    slug: 'chaves',
    displayName: 'Chaves',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.74,
    lng: -7.47,
    aliases: [],
    wikidataId: null,
    vibes: ['thermal', 'fortified', 'provincial'],
    svgCitiesSlug: 'pt-chaves',
  },
  {
    slug: 'guimaraes',
    displayName: 'Guimaraes',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.44,
    lng: -8.29,
    aliases: [],
    wikidataId: null,
    vibes: ['medieval', 'birthplace-proud', 'storied'],
    svgCitiesSlug: 'pt-guimaraes',
  },
  {
    slug: 'leiria',
    displayName: 'Leiria',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 39.74,
    lng: -8.81,
    aliases: [],
    wikidataId: null,
    vibes: ['castle-topped', 'pine-scented', 'central'],
    svgCitiesSlug: 'pt-leiria',
  },
  {
    slug: 'matosinhos',
    displayName: 'Matosinhos',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.18,
    lng: -8.69,
    aliases: [],
    wikidataId: null,
    vibes: ['oceanic', 'grilled-fish-scented', 'beachside'],
    svgCitiesSlug: 'pt-matosinhos',
  },
  {
    slug: 'nazare',
    displayName: 'Nazare',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 39.60,
    lng: -9.07,
    aliases: [],
    wikidataId: null,
    vibes: ['wave-battered', 'fishing-village', 'pious'],
    svgCitiesSlug: 'pt-nazare',
  },
  {
    slug: 'porto',
    displayName: 'Porto',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.15,
    lng: -8.61,
    aliases: [],
    wikidataId: null,
    vibes: ['soulful', 'port-wine-soaked', 'steep'],
    svgCitiesSlug: 'pt-porto',
  },
  {
    slug: 'viana-do-castelo',
    displayName: 'Viana do Castelo',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.69,
    lng: -8.83,
    aliases: [],
    wikidataId: null,
    vibes: ['folkloric', 'maritime', 'traditional'],
    svgCitiesSlug: 'pt-viana-do-castelo',
  },
  {
    slug: 'vila-real',
    displayName: 'Vila Real',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 41.30,
    lng: -7.74,
    aliases: [],
    wikidataId: null,
    vibes: ['thermal', 'mountainous', 'peaceful'],
    svgCitiesSlug: 'pt-vila-real',
  },
  {
    slug: 'bucharest',
    displayName: 'Bucharest',
    country: 'Romania',
    countryCode: 'RO',
    iana: 'Europe/Bucharest',
    lat: 44.43,
    lng: 26.10,
    aliases: [],
    wikidataId: null,
    vibes: ['crumbling', 'belle-epoque', 'chaotic'],
    svgCitiesSlug: 'ro-bucharest',
  },
  {
    slug: 'belgrade',
    displayName: 'Belgrade',
    country: 'Serbia',
    countryCode: 'RS',
    iana: 'Europe/Belgrade',
    lat: 44.79,
    lng: 20.47,
    aliases: [],
    wikidataId: null,
    vibes: ['defiant', 'nightlife-charged', 'balkan'],
    svgCitiesSlug: 'rs-belgrade',
  },
  {
    slug: 'subotica',
    displayName: 'Subotica',
    country: 'Serbia',
    countryCode: 'RS',
    iana: 'Europe/Belgrade',
    lat: 46.10,
    lng: 19.66,
    aliases: [],
    wikidataId: null,
    vibes: ['art-nouveau', 'multicultural', 'provincial'],
    svgCitiesSlug: 'rs-subotica',
  },
  {
    slug: 'murmansk',
    displayName: 'Murmansk',
    country: 'Russia',
    countryCode: 'RU',
    iana: 'Europe/Moscow',
    lat: 68.97,
    lng: 33.07,
    aliases: [],
    wikidataId: null,
    vibes: ['polar', 'darkened', 'hardy'],
    svgCitiesSlug: 'ru-murmansk',
  },
  {
    slug: 'st-petersburg',
    displayName: 'St. Petersburg',
    country: 'Russia',
    countryCode: 'RU',
    iana: 'Europe/Moscow',
    lat: 59.93,
    lng: 30.32,
    aliases: [],
    wikidataId: null,
    vibes: ['imperial', 'melancholic', 'grand'],
    svgCitiesSlug: null,
  },
  {
    slug: 'tula',
    displayName: 'Tula',
    country: 'Russia',
    countryCode: 'RU',
    iana: 'Europe/Moscow',
    lat: 54.19,
    lng: 37.62,
    aliases: [],
    wikidataId: null,
    vibes: ['stoic', 'industrial', 'resilient'],
    svgCitiesSlug: 'ru-tula',
  },
  {
    slug: 'yakutsk',
    displayName: 'Yakutsk',
    country: 'Russia',
    countryCode: 'RU',
    iana: 'Asia/Yakutsk',
    lat: 62.03,
    lng: 129.73,
    aliases: [],
    wikidataId: null,
    vibes: ['frozen', 'isolated', 'extreme'],
    svgCitiesSlug: 'ru-yakutsk',
  },
  {
    slug: 'ljubljana',
    displayName: 'Ljubljana',
    country: 'Slovenia',
    countryCode: 'SI',
    iana: 'Europe/Ljubljana',
    lat: 46.06,
    lng: 14.51,
    aliases: [],
    wikidataId: null,
    vibes: ['charming', 'laid-back', 'green'],
    svgCitiesSlug: 'si-ljubljana',
  },
  {
    slug: 'bratislava',
    displayName: 'Bratislava',
    country: 'Slovakia',
    countryCode: 'SK',
    iana: 'Europe/Bratislava',
    lat: 48.15,
    lng: 17.11,
    aliases: [],
    wikidataId: null,
    vibes: ['quiet', 'unassuming', 'emerging'],
    svgCitiesSlug: 'sk-bratislava',
  },
  {
    slug: 'san-marino',
    displayName: 'San Marino',
    country: 'San Marino',
    countryCode: 'SM',
    iana: 'Europe/San_Marino',
    lat: 43.94,
    lng: 12.45,
    aliases: [],
    wikidataId: null,
    vibes: ['serene', 'timeless', 'elevated'],
    svgCitiesSlug: 'sm-san-marino',
  },
  {
    slug: 'kyiv',
    displayName: 'Kyiv',
    country: 'Ukraine',
    countryCode: 'UA',
    iana: 'Europe/Kyiv',
    lat: 50.45,
    lng: 30.52,
    aliases: [],
    wikidataId: null,
    vibes: ['golden', 'spirited', 'ancient'],
    svgCitiesSlug: 'ua-kyiv',
  },
  {
    slug: 'odessa',
    displayName: 'Odessa',
    country: 'Ukraine',
    countryCode: 'UA',
    iana: 'Europe/Kyiv',
    lat: 46.48,
    lng: 30.73,
    aliases: [],
    wikidataId: null,
    vibes: ['witty', 'cosmopolitan', 'breezy'],
    svgCitiesSlug: 'ua-odessa',
  },
  {
    slug: 'liverpool',
    displayName: 'Liverpool',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 53.41,
    lng: -2.98,
    aliases: [],
    wikidataId: null,
    vibes: ['gritty', 'musical', 'proud'],
    svgCitiesSlug: 'uk-liverpool',
  },
  {
    slug: 'vatican-city',
    displayName: 'Vatican City',
    country: 'Vatican City',
    countryCode: 'VA',
    iana: 'Europe/Vatican',
    lat: 41.90,
    lng: 12.45,
    aliases: [],
    wikidataId: null,
    vibes: ['reverent', 'sacred', 'hushed'],
    svgCitiesSlug: 'va-vatican',
  },
  {
    slug: 'pristina',
    displayName: 'Pristina',
    country: 'Kosovo',
    countryCode: 'XK',
    iana: 'Europe/Belgrade',
    lat: 42.66,
    lng: 21.17,
    aliases: [],
    wikidataId: null,
    vibes: ['youthful', 'defiant', 'raw'],
    svgCitiesSlug: 'xk-pristina',
  },

  // --- Africa ---
  {
    slug: 'cairo',
    displayName: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    iana: 'Africa/Cairo',
    lat: 30.05,
    lng: 31.25,
    aliases: ['egypt'],
    wikidataId: null,
    vibes: ['ancient', 'chaotic', 'timeless'],
    svgCitiesSlug: 'eg-cairo',
  },
  {
    slug: 'johannesburg',
    displayName: 'Johannesburg',
    country: 'South Africa',
    countryCode: 'ZA',
    iana: 'Africa/Johannesburg',
    lat: -26.17,
    lng: 28.03,
    aliases: ['south africa'],
    wikidataId: null,
    vibes: ['ambitious', 'golden', 'resilient'],
    svgCitiesSlug: null,
  },
  {
    slug: 'cape-town',
    displayName: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    iana: 'Africa/Johannesburg',
    lat: -33.92,
    lng: 18.43,
    aliases: [],
    wikidataId: null,
    vibes: ['stunning', 'breezy', 'wild'],
    svgCitiesSlug: 'za-cape-town',
  },
  {
    slug: 'lagos',
    displayName: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    iana: 'Africa/Lagos',
    lat: 6.44,
    lng: 3.39,
    aliases: ['nigeria'],
    wikidataId: null,
    vibes: ['hustling', 'loud', 'unstoppable'],
    svgCitiesSlug: 'ng-lagos',
  },
  {
    slug: 'nairobi',
    displayName: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    iana: 'Africa/Nairobi',
    lat: -1.28,
    lng: 36.82,
    aliases: ['kenya'],
    wikidataId: null,
    vibes: ['enterprising', 'sunny', 'rising'],
    svgCitiesSlug: 'ke-nairobi',
  },
  {
    slug: 'ouagadougou',
    displayName: 'Ouagadougou',
    country: 'Burkina Faso',
    countryCode: 'BF',
    iana: 'Africa/Ouagadougou',
    lat: 12.37,
    lng: -1.52,
    aliases: [],
    wikidataId: null,
    vibes: ['dusty', 'warm', 'resilient'],
    svgCitiesSlug: 'bf-ouagadougou',
  },
  {
    slug: 'lalibela',
    displayName: 'Lalibela',
    country: 'Ethiopia',
    countryCode: 'ET',
    iana: 'Africa/Addis_Ababa',
    lat: 12.03,
    lng: 39.04,
    aliases: [],
    wikidataId: null,
    vibes: ['mystical', 'devotional', 'ancient'],
    svgCitiesSlug: 'et-lalibela',
  },
  {
    slug: 'addis-ababa',
    displayName: 'Addis Ababa',
    country: 'Ethiopia',
    countryCode: 'ET',
    iana: 'Africa/Addis_Ababa',
    lat: 9.02,
    lng: 38.75,
    aliases: [],
    wikidataId: null,
    vibes: ['bustling', 'hopeful', 'high'],
    svgCitiesSlug: null,
  },
  {
    slug: 'accra',
    displayName: 'Accra',
    country: 'Ghana',
    countryCode: 'GH',
    iana: 'Africa/Accra',
    lat: 5.56,
    lng: -0.19,
    aliases: [],
    wikidataId: null,
    vibes: ['vibrant', 'welcoming', 'humid'],
    svgCitiesSlug: 'gh-accra',
  },
  {
    slug: 'abidjan',
    displayName: 'Abidjan',
    country: 'Ivory Coast',
    countryCode: 'CI',
    iana: 'Africa/Abidjan',
    lat: 5.36,
    lng: -4.01,
    aliases: [],
    wikidataId: null,
    vibes: ['dynamic', 'tropical', 'ambitious'],
    svgCitiesSlug: null,
  },
  {
    slug: 'kinshasa',
    displayName: 'Kinshasa',
    country: 'DR Congo',
    countryCode: 'CD',
    iana: 'Africa/Kinshasa',
    lat: -4.32,
    lng: 15.31,
    aliases: [],
    wikidataId: null,
    vibes: ['frenetic', 'rhythmic', 'boundless'],
    svgCitiesSlug: null,
  },
  {
    slug: 'maseru',
    displayName: 'Maseru',
    country: 'Lesotho',
    countryCode: 'LS',
    iana: 'Africa/Maseru',
    lat: -29.31,
    lng: 27.48,
    aliases: [],
    wikidataId: null,
    vibes: ['windswept', 'rugged', 'quiet'],
    svgCitiesSlug: 'ls-maseru',
  },
  {
    slug: 'benghazi',
    displayName: 'Benghazi',
    country: 'Libya',
    countryCode: 'LY',
    iana: 'Africa/Tripoli',
    lat: 32.12,
    lng: 20.09,
    aliases: [],
    wikidataId: null,
    vibes: ['weathered', 'tense', 'coastal'],
    svgCitiesSlug: 'ly-benghazi',
  },
  {
    slug: 'casablanca',
    displayName: 'Casablanca',
    country: 'Morocco',
    countryCode: 'MA',
    iana: 'Africa/Casablanca',
    lat: 33.57,
    lng: -7.59,
    aliases: [],
    wikidataId: null,
    vibes: ['bustling', 'cinematic', 'salty'],
    svgCitiesSlug: 'ma-casablanca',
  },
  {
    slug: 'fez',
    displayName: 'Fez',
    country: 'Morocco',
    countryCode: 'MA',
    iana: 'Africa/Casablanca',
    lat: 34.03,
    lng: -5.00,
    aliases: [],
    wikidataId: null,
    vibes: ['labyrinthine', 'ancient', 'aromatic'],
    svgCitiesSlug: 'ma-fez',
  },
  {
    slug: 'marrakesh',
    displayName: 'Marrakesh',
    country: 'Morocco',
    countryCode: 'MA',
    iana: 'Africa/Casablanca',
    lat: 31.63,
    lng: -8.01,
    aliases: [],
    wikidataId: null,
    vibes: ['intoxicating', 'spicy', 'ochre'],
    svgCitiesSlug: 'ma-marrakesh',
  },
  {
    slug: 'antananarivo',
    displayName: 'Antananarivo',
    country: 'Madagascar',
    countryCode: 'MG',
    iana: 'Indian/Antananarivo',
    lat: -18.91,
    lng: 47.52,
    aliases: [],
    wikidataId: null,
    vibes: ['hilly', 'chaotic', 'resourceful'],
    svgCitiesSlug: 'mg-antananarivo',
  },
  {
    slug: 'maputo',
    displayName: 'Maputo',
    country: 'Mozambique',
    countryCode: 'MZ',
    iana: 'Africa/Maputo',
    lat: -25.97,
    lng: 32.58,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'rhythmic', 'languid'],
    svgCitiesSlug: 'mz-maputo',
  },
  {
    slug: 'windhoek',
    displayName: 'Windhoek',
    country: 'Namibia',
    countryCode: 'NA',
    iana: 'Africa/Windhoek',
    lat: -22.57,
    lng: 17.08,
    aliases: [],
    wikidataId: null,
    vibes: ['crisp', 'spacious', 'sunlit'],
    svgCitiesSlug: 'na-windhoek',
  },
  {
    slug: 'kigali',
    displayName: 'Kigali',
    country: 'Rwanda',
    countryCode: 'RW',
    iana: 'Africa/Kigali',
    lat: -1.94,
    lng: 29.87,
    aliases: [],
    wikidataId: null,
    vibes: ['clean', 'orderly', 'rising'],
    svgCitiesSlug: 'rw-kigali',
  },
  {
    slug: 'dakar',
    displayName: 'Dakar',
    country: 'Senegal',
    countryCode: 'SN',
    iana: 'Africa/Dakar',
    lat: 14.69,
    lng: -17.44,
    aliases: [],
    wikidataId: null,
    vibes: ['colorful', 'musical', 'coastal'],
    svgCitiesSlug: 'sn-dakar',
  },
  {
    slug: 'dar-es-salaam',
    displayName: 'Dar es Salaam',
    country: 'Tanzania',
    countryCode: 'TZ',
    iana: 'Africa/Dar_es_Salaam',
    lat: -6.79,
    lng: 39.28,
    aliases: [],
    wikidataId: null,
    vibes: ['humid', 'bustling', 'swahili'],
    svgCitiesSlug: null,
  },
  {
    slug: 'zanzibar',
    displayName: 'Zanzibar',
    country: 'Tanzania',
    countryCode: 'TZ',
    iana: 'Africa/Dar_es_Salaam',
    lat: -6.16,
    lng: 39.19,
    aliases: [],
    wikidataId: null,
    vibes: ['spiced', 'turquoise', 'timeless'],
    svgCitiesSlug: 'tz-zanzibar',
  },
  {
    slug: 'tunis',
    displayName: 'Tunis',
    country: 'Tunisia',
    countryCode: 'TN',
    iana: 'Africa/Tunis',
    lat: 36.81,
    lng: 10.17,
    aliases: [],
    wikidataId: null,
    vibes: ['mediterranean', 'refined', 'layered'],
    svgCitiesSlug: 'tn-tunis',
  },
  {
    slug: 'kampala',
    displayName: 'Kampala',
    country: 'Uganda',
    countryCode: 'UG',
    iana: 'Africa/Kampala',
    lat: 0.35,
    lng: 32.58,
    aliases: [],
    wikidataId: null,
    vibes: ['green', 'hilly', 'lively'],
    svgCitiesSlug: null,
  },
  {
    slug: 'lusaka',
    displayName: 'Lusaka',
    country: 'Zambia',
    countryCode: 'ZM',
    iana: 'Africa/Lusaka',
    lat: -15.39,
    lng: 28.32,
    aliases: [],
    wikidataId: null,
    vibes: ['warm', 'dusty', 'easy-going'],
    svgCitiesSlug: null,
  },
  {
    slug: 'algiers',
    displayName: 'Algiers',
    country: 'Algeria',
    countryCode: 'DZ',
    iana: 'Africa/Algiers',
    lat: 36.75,
    lng: 3.04,
    aliases: [],
    wikidataId: null,
    vibes: ['white', 'steep', 'nostalgic'],
    svgCitiesSlug: null,
  },

  // --- Middle East ---
  {
    slug: 'dubai',
    displayName: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    iana: 'Asia/Dubai',
    lat: 25.23,
    lng: 55.28,
    aliases: ['uae'],
    wikidataId: null,
    vibes: ['opulent', 'futuristic', 'dazzling'],
    svgCitiesSlug: 'ae-dubai',
  },
  {
    slug: 'riyadh',
    displayName: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    iana: 'Asia/Riyadh',
    lat: 24.64,
    lng: 46.77,
    aliases: ['saudi arabia'],
    wikidataId: null,
    vibes: ['vast', 'ambitious', 'scorching'],
    svgCitiesSlug: 'sa-riyadh',
  },
  {
    slug: 'jerusalem',
    displayName: 'Jerusalem',
    country: 'Israel',
    countryCode: 'IL',
    iana: 'Asia/Jerusalem',
    lat: 31.78,
    lng: 35.21,
    aliases: ['israel'],
    wikidataId: null,
    vibes: ['sacred', 'ancient', 'layered'],
    svgCitiesSlug: 'il-jerusalem',
  },
  {
    slug: 'abu-dhabi',
    displayName: 'Abu Dhabi',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    iana: 'Asia/Dubai',
    lat: 24.45,
    lng: 54.65,
    aliases: [],
    wikidataId: null,
    vibes: ['opulent', 'sleek', 'air-conditioned'],
    svgCitiesSlug: 'ae-abu-dhabi',
  },
  {
    slug: 'manama',
    displayName: 'Manama',
    country: 'Bahrain',
    countryCode: 'BH',
    iana: 'Asia/Bahrain',
    lat: 26.23,
    lng: 50.59,
    aliases: [],
    wikidataId: null,
    vibes: ['cosmopolitan', 'balmy', 'relaxed'],
    svgCitiesSlug: 'bh-manama',
  },
  {
    slug: 'haifa',
    displayName: 'Haifa',
    country: 'Israel',
    countryCode: 'IL',
    iana: 'Asia/Jerusalem',
    lat: 32.79,
    lng: 34.99,
    aliases: [],
    wikidataId: null,
    vibes: ['terraced', 'diverse', 'breezy'],
    svgCitiesSlug: 'il-haifa',
  },
  {
    slug: 'tel-aviv',
    displayName: 'Tel Aviv',
    country: 'Israel',
    countryCode: 'IL',
    iana: 'Asia/Jerusalem',
    lat: 32.07,
    lng: 34.78,
    aliases: [],
    wikidataId: null,
    vibes: ['hedonistic', 'sun-drenched', 'electric'],
    svgCitiesSlug: 'il-tel-aviv',
  },
  {
    slug: 'baghdad',
    displayName: 'Baghdad',
    country: 'Iraq',
    countryCode: 'IQ',
    iana: 'Asia/Baghdad',
    lat: 33.31,
    lng: 44.37,
    aliases: [],
    wikidataId: null,
    vibes: ['ancient', 'complex', 'resilient'],
    svgCitiesSlug: null,
  },
  {
    slug: 'samarra',
    displayName: 'Samarra',
    country: 'Iraq',
    countryCode: 'IQ',
    iana: 'Asia/Baghdad',
    lat: 34.20,
    lng: 43.88,
    aliases: [],
    wikidataId: null,
    vibes: ['sacred', 'timeworn', 'dusty'],
    svgCitiesSlug: 'iq-samarra',
  },
  {
    slug: 'isfahan',
    displayName: 'Isfahan',
    country: 'Iran',
    countryCode: 'IR',
    iana: 'Asia/Tehran',
    lat: 32.65,
    lng: 51.68,
    aliases: [],
    wikidataId: null,
    vibes: ['turquoise', 'poetic', 'elegant'],
    svgCitiesSlug: 'ir-isfahan',
  },
  {
    slug: 'mashhad',
    displayName: 'Mashhad',
    country: 'Iran',
    countryCode: 'IR',
    iana: 'Asia/Tehran',
    lat: 36.30,
    lng: 59.60,
    aliases: [],
    wikidataId: null,
    vibes: ['devotional', 'bustling', 'pilgrimage-bound'],
    svgCitiesSlug: 'ir-mashhad',
  },
  {
    slug: 'tehran',
    displayName: 'Tehran',
    country: 'Iran',
    countryCode: 'IR',
    iana: 'Asia/Tehran',
    lat: 35.69,
    lng: 51.39,
    aliases: [],
    wikidataId: null,
    vibes: ['mountainous', 'dynamic', 'sprawling'],
    svgCitiesSlug: 'ir-tehran',
  },
  {
    slug: 'amman',
    displayName: 'Amman',
    country: 'Jordan',
    countryCode: 'JO',
    iana: 'Asia/Amman',
    lat: 31.95,
    lng: 35.93,
    aliases: [],
    wikidataId: null,
    vibes: ['sandy', 'hilly', 'welcoming'],
    svgCitiesSlug: 'jo-amman',
  },
  {
    slug: 'kuwait-city',
    displayName: 'Kuwait City',
    country: 'Kuwait',
    countryCode: 'KW',
    iana: 'Asia/Kuwait',
    lat: 29.38,
    lng: 47.99,
    aliases: [],
    wikidataId: null,
    vibes: ['gleaming', 'modern', 'sweltering'],
    svgCitiesSlug: 'kw-kuwait',
  },
  {
    slug: 'beirut',
    displayName: 'Beirut',
    country: 'Lebanon',
    countryCode: 'LB',
    iana: 'Asia/Beirut',
    lat: 33.89,
    lng: 35.50,
    aliases: [],
    wikidataId: null,
    vibes: ['resilient', 'cultured', 'phoenician'],
    svgCitiesSlug: 'lb-beirut',
  },
  {
    slug: 'muscat',
    displayName: 'Muscat',
    country: 'Oman',
    countryCode: 'OM',
    iana: 'Asia/Muscat',
    lat: 23.59,
    lng: 58.54,
    aliases: [],
    wikidataId: null,
    vibes: ['fragrant', 'serene', 'white-washed'],
    svgCitiesSlug: 'om-muscat',
  },
  {
    slug: 'doha',
    displayName: 'Doha',
    country: 'Qatar',
    countryCode: 'QA',
    iana: 'Asia/Qatar',
    lat: 25.29,
    lng: 51.53,
    aliases: [],
    wikidataId: null,
    vibes: ['gleaming', 'ambitious', 'modern'],
    svgCitiesSlug: 'qa-doha',
  },
  {
    slug: 'jeddah',
    displayName: 'Jeddah',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    iana: 'Asia/Riyadh',
    lat: 21.49,
    lng: 39.19,
    aliases: [],
    wikidataId: null,
    vibes: ['humid', 'cosmopolitan', 'gateway-like'],
    svgCitiesSlug: null,
  },

  // --- Asia ---
  {
    slug: 'tokyo',
    displayName: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 35.69,
    lng: 139.75,
    aliases: ['japan'],
    wikidataId: null,
    vibes: ['zen', 'precise', 'futuristic'],
    svgCitiesSlug: 'jp-tokyo',
  },
  {
    slug: 'osaka',
    displayName: 'Osaka',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 34.75,
    lng: 135.46,
    aliases: [],
    wikidataId: null,
    vibes: ['playful', 'flavorful', 'neon'],
    svgCitiesSlug: null,
  },
  {
    slug: 'seoul',
    displayName: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    iana: 'Asia/Seoul',
    lat: 37.57,
    lng: 127.00,
    aliases: ['korea', 'south korea'],
    wikidataId: null,
    vibes: ['trendy', 'fast-paced', 'glossy'],
    svgCitiesSlug: 'kr-seoul',
  },
  {
    slug: 'shanghai',
    displayName: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 31.22,
    lng: 121.44,
    aliases: ['china'],
    wikidataId: null,
    vibes: ['electric', 'towering', 'relentless'],
    svgCitiesSlug: 'cn-shanghai',
  },
  {
    slug: 'beijing',
    displayName: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 39.93,
    lng: 116.39,
    aliases: [],
    wikidataId: null,
    vibes: ['imperial', 'vast', 'storied'],
    svgCitiesSlug: 'cn-beijing',
  },
  {
    slug: 'hong-kong',
    displayName: 'Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    iana: 'Asia/Hong_Kong',
    lat: 22.30,
    lng: 114.19,
    aliases: ['hk'],
    wikidataId: null,
    vibes: ['dense', 'neon', 'kinetic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'singapore',
    displayName: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    iana: 'Asia/Singapore',
    lat: 1.29,
    lng: 103.86,
    aliases: ['sg'],
    wikidataId: null,
    vibes: ['orderly', 'lush', 'spotless'],
    svgCitiesSlug: null,
  },
  {
    slug: 'bangkok',
    displayName: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    iana: 'Asia/Bangkok',
    lat: 13.75,
    lng: 100.52,
    aliases: ['bkk', 'thailand'],
    wikidataId: null,
    vibes: ['steamy', 'chaotic', 'golden'],
    svgCitiesSlug: null,
  },
  {
    slug: 'mumbai',
    displayName: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 19.02,
    lng: 72.86,
    aliases: ['india'],
    wikidataId: null,
    vibes: ['intense', 'cinematic', 'teeming'],
    svgCitiesSlug: null,
  },
  {
    slug: 'delhi',
    displayName: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 28.67,
    lng: 77.23,
    aliases: [],
    wikidataId: null,
    vibes: ['spicy', 'historic', 'vibrant'],
    svgCitiesSlug: 'in-delhi',
  },
  {
    slug: 'karachi',
    displayName: 'Karachi',
    country: 'Pakistan',
    countryCode: 'PK',
    iana: 'Asia/Karachi',
    lat: 24.87,
    lng: 66.99,
    aliases: ['pakistan'],
    wikidataId: null,
    vibes: ['gritty', 'sprawling', 'spirited'],
    svgCitiesSlug: 'pk-karachi',
  },
  {
    slug: 'dhaka',
    displayName: 'Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    iana: 'Asia/Dhaka',
    lat: 23.72,
    lng: 90.41,
    aliases: ['bangladesh'],
    wikidataId: null,
    vibes: ['dense', 'lively', 'colorful'],
    svgCitiesSlug: 'bd-dhaka',
  },
  {
    slug: 'ho-chi-minh-city',
    displayName: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    iana: 'Asia/Ho_Chi_Minh',
    lat: 10.78,
    lng: 106.70,
    aliases: ['vietnam'],
    wikidataId: null,
    vibes: ['buzzing', 'aromatic', 'warm'],
    svgCitiesSlug: null,
  },
  {
    slug: 'jakarta',
    displayName: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    iana: 'Asia/Jakarta',
    lat: -6.17,
    lng: 106.83,
    aliases: ['indonesia'],
    wikidataId: null,
    vibes: ['tropical', 'sprawling', 'lively'],
    svgCitiesSlug: null,
  },
  {
    slug: 'kuala-lumpur',
    displayName: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    iana: 'Asia/Kuala_Lumpur',
    lat: 3.17,
    lng: 101.70,
    aliases: ['malaysia'],
    wikidataId: null,
    vibes: ['gleaming', 'tropical', 'diverse'],
    svgCitiesSlug: 'my-kuala-lumpur',
  },
  {
    slug: 'manila',
    displayName: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    iana: 'Asia/Manila',
    lat: 14.60,
    lng: 120.98,
    aliases: ['philippines'],
    wikidataId: null,
    vibes: ['cheerful', 'resilient', 'warm'],
    svgCitiesSlug: 'ph-manila',
  },
  {
    slug: 'taipei',
    displayName: 'Taipei',
    country: 'Taiwan',
    countryCode: 'TW',
    iana: 'Asia/Taipei',
    lat: 25.04,
    lng: 121.57,
    aliases: ['taiwan'],
    wikidataId: null,
    vibes: ['inventive', 'nocturnal', 'sweet'],
    svgCitiesSlug: 'tw-taipei',
  },
  {
    slug: 'kathmandu',
    displayName: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    iana: 'Asia/Kathmandu',
    lat: 27.72,
    lng: 85.32,
    aliases: [],
    wikidataId: null,
    vibes: ['spiritual', 'high', 'serene'],
    svgCitiesSlug: 'np-kathmandu',
  },
  {
    slug: 'yerevan',
    displayName: 'Yerevan',
    country: 'Armenia',
    countryCode: 'AM',
    iana: 'Asia/Yerevan',
    lat: 40.18,
    lng: 44.51,
    aliases: [],
    wikidataId: null,
    vibes: ['rosy', 'ancient', 'soviet-tinged'],
    svgCitiesSlug: 'am-yerevan',
  },
  {
    slug: 'seria',
    displayName: 'Seria',
    country: 'Brunei',
    countryCode: 'BN',
    iana: 'Asia/Brunei',
    lat: 4.61,
    lng: 114.32,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'quiet', 'industrial'],
    svgCitiesSlug: 'bn-seria',
  },
  {
    slug: 'thimphu',
    displayName: 'Thimphu',
    country: 'Bhutan',
    countryCode: 'BT',
    iana: 'Asia/Thimphu',
    lat: 27.47,
    lng: 89.64,
    aliases: [],
    wikidataId: null,
    vibes: ['peaceful', 'buddhist', 'mountain-fresh'],
    svgCitiesSlug: 'bt-thimphu',
  },
  {
    slug: 'chengdu',
    displayName: 'Chengdu',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 30.57,
    lng: 104.07,
    aliases: [],
    wikidataId: null,
    vibes: ['spicy', 'laid-back', 'misty'],
    svgCitiesSlug: 'cn-chengdu',
  },
  {
    slug: 'jingzhou',
    displayName: 'Jingzhou',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 30.33,
    lng: 112.19,
    aliases: [],
    wikidataId: null,
    vibes: ['historic', 'riverside', 'tranquil'],
    svgCitiesSlug: 'cn-jingzhou',
  },
  {
    slug: 'leshan',
    displayName: 'Leshan',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 29.55,
    lng: 103.77,
    aliases: [],
    wikidataId: null,
    vibes: ['peaceful', 'meditative', 'riverside'],
    svgCitiesSlug: 'cn-leshan',
  },
  {
    slug: 'shenzhen',
    displayName: 'Shenzhen',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 22.54,
    lng: 114.06,
    aliases: [],
    wikidataId: null,
    vibes: ['ambitious', 'innovative', 'frenetic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'guangzhou',
    displayName: 'Guangzhou',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 23.13,
    lng: 113.26,
    aliases: [],
    wikidataId: null,
    vibes: ['steamy', 'mercantile', 'bold'],
    svgCitiesSlug: null,
  },
  {
    slug: 'chongqing',
    displayName: 'Chongqing',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 29.56,
    lng: 106.55,
    aliases: [],
    wikidataId: null,
    vibes: ['fiery', 'foggy', 'sprawling'],
    svgCitiesSlug: null,
  },
  {
    slug: 'wuhan',
    displayName: 'Wuhan',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 30.59,
    lng: 114.31,
    aliases: [],
    wikidataId: null,
    vibes: ['riverside', 'industrial', 'hot'],
    svgCitiesSlug: null,
  },
  {
    slug: 'denpasar',
    displayName: 'Denpasar',
    country: 'Indonesia',
    countryCode: 'ID',
    iana: 'Asia/Makassar',
    lat: -8.65,
    lng: 115.22,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'spiritual', 'languid'],
    svgCitiesSlug: 'id-denpasar',
  },
  {
    slug: 'surabaya',
    displayName: 'Surabaya',
    country: 'Indonesia',
    countryCode: 'ID',
    iana: 'Asia/Jakarta',
    lat: -7.25,
    lng: 112.75,
    aliases: [],
    wikidataId: null,
    vibes: ['hot', 'gritty', 'industrial'],
    svgCitiesSlug: null,
  },
  {
    slug: 'agra',
    displayName: 'Agra',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 27.18,
    lng: 78.02,
    aliases: [],
    wikidataId: null,
    vibes: ['monumental', 'hazy', 'timeless'],
    svgCitiesSlug: 'in-agra',
  },
  {
    slug: 'kolkata',
    displayName: 'Kolkata',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 22.57,
    lng: 88.36,
    aliases: [],
    wikidataId: null,
    vibes: ['literary', 'humid', 'intense'],
    svgCitiesSlug: null,
  },
  {
    slug: 'bangalore',
    displayName: 'Bangalore',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 12.97,
    lng: 77.59,
    aliases: [],
    wikidataId: null,
    vibes: ['cosmopolitan', 'temperate', 'innovative'],
    svgCitiesSlug: null,
  },
  {
    slug: 'chennai',
    displayName: 'Chennai',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 13.08,
    lng: 80.27,
    aliases: [],
    wikidataId: null,
    vibes: ['hot', 'traditional', 'coastal'],
    svgCitiesSlug: null,
  },
  {
    slug: 'hyderabad',
    displayName: 'Hyderabad',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 17.38,
    lng: 78.49,
    aliases: [],
    wikidataId: null,
    vibes: ['spiced', 'historic', 'tech-savvy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'kyoto',
    displayName: 'Kyoto',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 35.01,
    lng: 135.77,
    aliases: [],
    wikidataId: null,
    vibes: ['tranquil', 'refined', 'timeless'],
    svgCitiesSlug: 'jp-kyoto',
  },
  {
    slug: 'nara',
    displayName: 'Nara',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 34.69,
    lng: 135.80,
    aliases: [],
    wikidataId: null,
    vibes: ['gentle', 'sacred', 'serene'],
    svgCitiesSlug: 'jp-nara',
  },
  {
    slug: 'shirakawa-go',
    displayName: 'Shirakawa-go',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 36.26,
    lng: 136.91,
    aliases: [],
    wikidataId: null,
    vibes: ['snowy', 'rustic', 'traditional'],
    svgCitiesSlug: 'jp-shirakawa-go',
  },
  {
    slug: 'sihanoukville',
    displayName: 'Sihanoukville',
    country: 'Cambodia',
    countryCode: 'KH',
    iana: 'Asia/Phnom_Penh',
    lat: 10.63,
    lng: 103.50,
    aliases: [],
    wikidataId: null,
    vibes: ['beachy', 'laid-back', 'tropical'],
    svgCitiesSlug: 'kh-sihanoukville',
  },
  {
    slug: 'phnom-penh',
    displayName: 'Phnom Penh',
    country: 'Cambodia',
    countryCode: 'KH',
    iana: 'Asia/Phnom_Penh',
    lat: 11.56,
    lng: 104.92,
    aliases: [],
    wikidataId: null,
    vibes: ['humid', 'chaotic', 'emerging'],
    svgCitiesSlug: null,
  },
  {
    slug: 'bishkek',
    displayName: 'Bishkek',
    country: 'Kyrgyzstan',
    countryCode: 'KG',
    iana: 'Asia/Bishkek',
    lat: 42.87,
    lng: 74.59,
    aliases: [],
    wikidataId: null,
    vibes: ['soviet', 'mountainous', 'fresh'],
    svgCitiesSlug: 'kg-bishkek',
  },
  {
    slug: 'pyongyang',
    displayName: 'Pyongyang',
    country: 'North Korea',
    countryCode: 'KP',
    iana: 'Asia/Pyongyang',
    lat: 39.02,
    lng: 125.75,
    aliases: [],
    wikidataId: null,
    vibes: ['austere', 'controlled', 'monumental'],
    svgCitiesSlug: 'kp-pyongyang',
  },
  {
    slug: 'busan',
    displayName: 'Busan',
    country: 'South Korea',
    countryCode: 'KR',
    iana: 'Asia/Seoul',
    lat: 35.18,
    lng: 129.08,
    aliases: [],
    wikidataId: null,
    vibes: ['coastal', 'breezy', 'relaxed'],
    svgCitiesSlug: null,
  },
  {
    slug: 'almaty',
    displayName: 'Almaty',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    iana: 'Asia/Almaty',
    lat: 43.24,
    lng: 76.95,
    aliases: [],
    wikidataId: null,
    vibes: ['mountainous', 'cosmopolitan', 'soviet-nostalgic'],
    svgCitiesSlug: 'kz-alma-aty',
  },
  {
    slug: 'astana',
    displayName: 'Astana',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    iana: 'Asia/Almaty',
    lat: 51.17,
    lng: 71.43,
    aliases: [],
    wikidataId: null,
    vibes: ['futuristic', 'windswept', 'ambitious'],
    svgCitiesSlug: 'kz-astana',
  },
  {
    slug: 'kostanay',
    displayName: 'Kostanay',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    iana: 'Asia/Kostanay',
    lat: 53.21,
    lng: 63.63,
    aliases: [],
    wikidataId: null,
    vibes: ['provincial', 'vast', 'quiet'],
    svgCitiesSlug: 'kz-kostanay',
  },
  {
    slug: 'schuchinsk',
    displayName: 'Schuchinsk',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    iana: 'Asia/Almaty',
    lat: 52.94,
    lng: 70.19,
    aliases: [],
    wikidataId: null,
    vibes: ['pine-scented', 'lakeside', 'peaceful'],
    svgCitiesSlug: 'kz-schuchinsk',
  },
  {
    slug: 'uralsk',
    displayName: 'Uralsk',
    country: 'Kazakhstan',
    countryCode: 'KZ',
    iana: 'Asia/Oral',
    lat: 51.23,
    lng: 51.37,
    aliases: [],
    wikidataId: null,
    vibes: ['frontier', 'spacious', 'remote'],
    svgCitiesSlug: 'kz-uralsk',
  },
  {
    slug: 'luang-prabang',
    displayName: 'Luang Prabang',
    country: 'Laos',
    countryCode: 'LA',
    iana: 'Asia/Vientiane',
    lat: 19.89,
    lng: 102.13,
    aliases: [],
    wikidataId: null,
    vibes: ['golden', 'tranquil', 'spiritual'],
    svgCitiesSlug: 'la-luang-prabang',
  },
  {
    slug: 'bagan',
    displayName: 'Bagan',
    country: 'Myanmar',
    countryCode: 'MM',
    iana: 'Asia/Yangon',
    lat: 21.17,
    lng: 94.86,
    aliases: [],
    wikidataId: null,
    vibes: ['mystical', 'ancient', 'dusty'],
    svgCitiesSlug: 'mm-bagan',
  },
  {
    slug: 'yangon',
    displayName: 'Yangon',
    country: 'Myanmar',
    countryCode: 'MM',
    iana: 'Asia/Yangon',
    lat: 16.87,
    lng: 96.20,
    aliases: [],
    wikidataId: null,
    vibes: ['golden', 'humid', 'timeless'],
    svgCitiesSlug: null,
  },
  {
    slug: 'ulaanbaatar',
    displayName: 'Ulaanbaatar',
    country: 'Mongolia',
    countryCode: 'MN',
    iana: 'Asia/Ulaanbaatar',
    lat: 47.92,
    lng: 106.92,
    aliases: [],
    wikidataId: null,
    vibes: ['harsh', 'nomadic', 'smoky'],
    svgCitiesSlug: 'mn-ulaanbaatar',
  },
  {
    slug: 'kuching',
    displayName: 'Kuching',
    country: 'Malaysia',
    countryCode: 'MY',
    iana: 'Asia/Kuching',
    lat: 1.55,
    lng: 110.34,
    aliases: [],
    wikidataId: null,
    vibes: ['riverside', 'laid-back', 'tropical'],
    svgCitiesSlug: 'my-kuching',
  },
  {
    slug: 'islamabad',
    displayName: 'Islamabad',
    country: 'Pakistan',
    countryCode: 'PK',
    iana: 'Asia/Karachi',
    lat: 33.69,
    lng: 73.04,
    aliases: [],
    wikidataId: null,
    vibes: ['green', 'planned', 'serene'],
    svgCitiesSlug: 'pk-islamabad',
  },
  {
    slug: 'lahore',
    displayName: 'Lahore',
    country: 'Pakistan',
    countryCode: 'PK',
    iana: 'Asia/Karachi',
    lat: 31.55,
    lng: 74.35,
    aliases: [],
    wikidataId: null,
    vibes: ['vibrant', 'historic', 'spicy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'cebu',
    displayName: 'Cebu',
    country: 'Philippines',
    countryCode: 'PH',
    iana: 'Asia/Manila',
    lat: 10.31,
    lng: 123.89,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'festive', 'coastal'],
    svgCitiesSlug: 'ph-cebu',
  },
  {
    slug: 'sentosa',
    displayName: 'Sentosa',
    country: 'Singapore',
    countryCode: 'SG',
    iana: 'Asia/Singapore',
    lat: 1.25,
    lng: 103.83,
    aliases: [],
    wikidataId: null,
    vibes: ['resort-like', 'manicured', 'playful'],
    svgCitiesSlug: 'sg-sentosa',
  },
  {
    slug: 'colombo',
    displayName: 'Colombo',
    country: 'Sri Lanka',
    countryCode: 'LK',
    iana: 'Asia/Colombo',
    lat: 6.93,
    lng: 79.85,
    aliases: [],
    wikidataId: null,
    vibes: ['humid', 'colonial', 'bustling'],
    svgCitiesSlug: null,
  },
  {
    slug: 'pattaya',
    displayName: 'Pattaya',
    country: 'Thailand',
    countryCode: 'TH',
    iana: 'Asia/Bangkok',
    lat: 12.93,
    lng: 100.88,
    aliases: [],
    wikidataId: null,
    vibes: ['neon', 'beachy', 'hedonistic'],
    svgCitiesSlug: 'th-pattaya',
  },
  {
    slug: 'dushanbe',
    displayName: 'Dushanbe',
    country: 'Tajikistan',
    countryCode: 'TJ',
    iana: 'Asia/Dushanbe',
    lat: 38.56,
    lng: 68.77,
    aliases: [],
    wikidataId: null,
    vibes: ['mountainous', 'soviet', 'leafy'],
    svgCitiesSlug: 'tj-dushanbe',
  },
  {
    slug: 'dili',
    displayName: 'Dili',
    country: 'Timor-Leste',
    countryCode: 'TL',
    iana: 'Asia/Dili',
    lat: -8.56,
    lng: 125.57,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'emerging', 'coastal'],
    svgCitiesSlug: 'tl-dili',
  },
  {
    slug: 'ashgabat',
    displayName: 'Ashgabat',
    country: 'Turkmenistan',
    countryCode: 'TM',
    iana: 'Asia/Ashgabat',
    lat: 37.96,
    lng: 58.38,
    aliases: [],
    wikidataId: null,
    vibes: ['marble', 'surreal', 'gleaming'],
    svgCitiesSlug: 'tm-ashgabat',
  },
  {
    slug: 'nukus',
    displayName: 'Nukus',
    country: 'Uzbekistan',
    countryCode: 'UZ',
    iana: 'Asia/Tashkent',
    lat: 42.46,
    lng: 59.60,
    aliases: [],
    wikidataId: null,
    vibes: ['remote', 'dusty', 'stark'],
    svgCitiesSlug: 'uz-nukus',
  },
  {
    slug: 'tashkent',
    displayName: 'Tashkent',
    country: 'Uzbekistan',
    countryCode: 'UZ',
    iana: 'Asia/Tashkent',
    lat: 41.30,
    lng: 69.28,
    aliases: [],
    wikidataId: null,
    vibes: ['soviet', 'sunny', 'spacious'],
    svgCitiesSlug: 'uz-tashkent',
  },
  {
    slug: 'hanoi',
    displayName: 'Hanoi',
    country: 'Vietnam',
    countryCode: 'VN',
    iana: 'Asia/Ho_Chi_Minh',
    lat: 21.03,
    lng: 105.85,
    aliases: [],
    wikidataId: null,
    vibes: ['motorbike-buzzing', 'aromatic', 'humid'],
    svgCitiesSlug: 'vn-hanoi',
  },
  {
    slug: 'vung-tau',
    displayName: 'Vung Tau',
    country: 'Vietnam',
    countryCode: 'VN',
    iana: 'Asia/Ho_Chi_Minh',
    lat: 10.35,
    lng: 107.08,
    aliases: [],
    wikidataId: null,
    vibes: ['breezy', 'coastal', 'relaxed'],
    svgCitiesSlug: 'vn-vung-tau',
  },

  // --- Oceania ---
  {
    slug: 'sydney',
    displayName: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Sydney',
    lat: -33.92,
    lng: 151.19,
    aliases: ['australia'],
    wikidataId: null,
    vibes: ['sunny', 'sparkling', 'coastal'],
    svgCitiesSlug: 'au-sydney',
  },
  {
    slug: 'melbourne',
    displayName: 'Melbourne',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Melbourne',
    lat: -37.82,
    lng: 144.98,
    aliases: [],
    wikidataId: null,
    vibes: ['artsy', 'caffeinated', 'eclectic'],
    svgCitiesSlug: 'au-melbourne',
  },
  {
    slug: 'auckland',
    displayName: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    iana: 'Pacific/Auckland',
    lat: -36.85,
    lng: 174.76,
    aliases: ['new zealand', 'nz'],
    wikidataId: null,
    vibes: ['adventurous', 'green', 'fresh'],
    svgCitiesSlug: null,
  },
  {
    slug: 'canberra',
    displayName: 'Canberra',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Sydney',
    lat: -35.28,
    lng: 149.13,
    aliases: [],
    wikidataId: null,
    vibes: ['planned', 'leafy', 'bureaucratic'],
    svgCitiesSlug: 'au-canberra',
  },
  {
    slug: 'hobart',
    displayName: 'Hobart',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Hobart',
    lat: -42.88,
    lng: 147.33,
    aliases: [],
    wikidataId: null,
    vibes: ['cool', 'maritime', 'artsy'],
    svgCitiesSlug: 'au-hobart',
  },
  {
    slug: 'perth',
    displayName: 'Perth',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Perth',
    lat: -31.95,
    lng: 115.86,
    aliases: [],
    wikidataId: null,
    vibes: ['sunny', 'isolated', 'relaxed'],
    svgCitiesSlug: 'au-perth',
  },
  {
    slug: 'suva',
    displayName: 'Suva',
    country: 'Fiji',
    countryCode: 'FJ',
    iana: 'Pacific/Fiji',
    lat: -18.14,
    lng: 178.44,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'humid', 'island-time'],
    svgCitiesSlug: 'fj-suva',
  },
  {
    slug: 'tarawa',
    displayName: 'Tarawa',
    country: 'Kiribati',
    countryCode: 'KI',
    iana: 'Pacific/Tarawa',
    lat: 1.45,
    lng: 173.00,
    aliases: [],
    wikidataId: null,
    vibes: ['remote', 'atoll-bound', 'lagoon-like'],
    svgCitiesSlug: 'ki-tarawa',
  },
  {
    slug: 'port-louis',
    displayName: 'Port Louis',
    country: 'Mauritius',
    countryCode: 'MU',
    iana: 'Indian/Mauritius',
    lat: -20.16,
    lng: 57.50,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'bustling', 'creole'],
    svgCitiesSlug: 'mu-port-louis',
  },
  {
    slug: 'noumea',
    displayName: 'Noumea',
    country: 'New Caledonia',
    countryCode: 'NC',
    iana: 'Pacific/Noumea',
    lat: -22.28,
    lng: 166.46,
    aliases: [],
    wikidataId: null,
    vibes: ['french', 'turquoise', 'resort-like'],
    svgCitiesSlug: 'nc-noumea',
  },
  {
    slug: 'wellington',
    displayName: 'Wellington',
    country: 'New Zealand',
    countryCode: 'NZ',
    iana: 'Pacific/Auckland',
    lat: -41.29,
    lng: 174.78,
    aliases: [],
    wikidataId: null,
    vibes: ['windy', 'creative', 'caffeinated'],
    svgCitiesSlug: 'nz-wellington',
  },
  {
    slug: 'honiara',
    displayName: 'Honiara',
    country: 'Solomon Islands',
    countryCode: 'SB',
    iana: 'Pacific/Guadalcanal',
    lat: -9.43,
    lng: 159.96,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'quiet', 'emerging'],
    svgCitiesSlug: 'sb-honiara',
  },
  {
    slug: 'nukualofa',
    displayName: "Nuku'alofa",
    country: 'Tonga',
    countryCode: 'TO',
    iana: 'Pacific/Tongatapu',
    lat: -21.21,
    lng: -175.20,
    aliases: [],
    wikidataId: null,
    vibes: ['remote', 'pacific', 'tranquil'],
    svgCitiesSlug: 'to-nukualofa',
  },
  {
    slug: 'funafuti',
    displayName: 'Funafuti',
    country: 'Tuvalu',
    countryCode: 'TV',
    iana: 'Pacific/Funafuti',
    lat: -8.52,
    lng: 179.20,
    aliases: [],
    wikidataId: null,
    vibes: ['tiny', 'coral', 'vulnerable'],
    svgCitiesSlug: 'tv-funafuti',
  },
  {
    slug: 'port-vila',
    displayName: 'Port Vila',
    country: 'Vanuatu',
    countryCode: 'VU',
    iana: 'Pacific/Efate',
    lat: -17.73,
    lng: 168.32,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'volcanic', 'laid-back'],
    svgCitiesSlug: 'vu-port-vila',
  },
  {
    slug: 'apia',
    displayName: 'Apia',
    country: 'Samoa',
    countryCode: 'WS',
    iana: 'Pacific/Apia',
    lat: -13.83,
    lng: -171.76,
    aliases: [],
    wikidataId: null,
    vibes: ['warm', 'polynesian', 'unhurried'],
    svgCitiesSlug: 'ws-apia',
  },

  // --- Central America & Caribbean ---
  {
    slug: 'saint-johns',
    displayName: "Saint John's",
    country: 'Antigua and Barbuda',
    countryCode: 'AG',
    iana: 'America/Antigua',
    lat: 17.12,
    lng: -61.84,
    aliases: [],
    wikidataId: null,
    vibes: ['turquoise', 'colonial', 'breezy'],
    svgCitiesSlug: 'ag-saint-john',
  },
  {
    slug: 'nassau',
    displayName: 'Nassau',
    country: 'Bahamas',
    countryCode: 'BS',
    iana: 'America/Nassau',
    lat: 25.06,
    lng: -77.35,
    aliases: [],
    wikidataId: null,
    vibes: ['turquoise', 'resort', 'tropical'],
    svgCitiesSlug: 'bs-nassau',
  },
  {
    slug: 'san-ignacio',
    displayName: 'San Ignacio',
    country: 'Belize',
    countryCode: 'BZ',
    iana: 'America/Belize',
    lat: 17.16,
    lng: -89.07,
    aliases: [],
    wikidataId: null,
    vibes: ['jungle-wrapped', 'mystical', 'adventurous'],
    svgCitiesSlug: 'bz-san-ignacio',
  },
  {
    slug: 'alajuela',
    displayName: 'Alajuela',
    country: 'Costa Rica',
    countryCode: 'CR',
    iana: 'America/Costa_Rica',
    lat: 10.02,
    lng: -84.22,
    aliases: [],
    wikidataId: null,
    vibes: ['tropical', 'verdant', 'volcanic'],
    svgCitiesSlug: 'cr-alajuela',
  },
  {
    slug: 'havana',
    displayName: 'Havana',
    country: 'Cuba',
    countryCode: 'CU',
    iana: 'America/Havana',
    lat: 23.11,
    lng: -82.37,
    aliases: [],
    wikidataId: null,
    vibes: ['nostalgic', 'sultry', 'rhythmic'],
    svgCitiesSlug: 'cu-havana',
  },
  {
    slug: 'willemstad',
    displayName: 'Willemstad',
    country: 'Curacao',
    countryCode: 'CW',
    iana: 'America/Curacao',
    lat: 12.11,
    lng: -68.94,
    aliases: [],
    wikidataId: null,
    vibes: ['pastel', 'breezy', 'dutch-tinged'],
    svgCitiesSlug: 'cw-willemstadt',
  },
  {
    slug: 'st-george',
    displayName: "St. George's",
    country: 'Grenada',
    countryCode: 'GD',
    iana: 'America/Grenada',
    lat: 12.05,
    lng: -61.75,
    aliases: [],
    wikidataId: null,
    vibes: ['colonial', 'cobblestoned', 'volcanic'],
    svgCitiesSlug: 'gd-st-george',
  },
  {
    slug: 'antigua-guatemala',
    displayName: 'Antigua Guatemala',
    country: 'Guatemala',
    countryCode: 'GT',
    iana: 'America/Guatemala',
    lat: 14.56,
    lng: -90.73,
    aliases: [],
    wikidataId: null,
    vibes: ['colonial', 'volcanic', 'cobblestoned'],
    svgCitiesSlug: 'gt-antigua',
  },
  {
    slug: 'georgetown',
    displayName: 'Georgetown',
    country: 'Guyana',
    countryCode: 'GY',
    iana: 'America/Guyana',
    lat: 6.80,
    lng: -58.16,
    aliases: [],
    wikidataId: null,
    vibes: ['wooden', 'tropical', 'colonial'],
    svgCitiesSlug: 'gy-georgetown',
  },
  {
    slug: 'tegucigalpa',
    displayName: 'Tegucigalpa',
    country: 'Honduras',
    countryCode: 'HN',
    iana: 'America/Tegucigalpa',
    lat: 14.07,
    lng: -87.19,
    aliases: [],
    wikidataId: null,
    vibes: ['mountainous', 'chaotic', 'resilient'],
    svgCitiesSlug: 'hn-tegucigalpa',
  },
  {
    slug: 'port-au-prince',
    displayName: 'Port-au-Prince',
    country: 'Haiti',
    countryCode: 'HT',
    iana: 'America/Port-au-Prince',
    lat: 18.54,
    lng: -72.34,
    aliases: [],
    wikidataId: null,
    vibes: ['vibrant', 'resilient', 'intense'],
    svgCitiesSlug: 'ht-port-au-prince',
  },
  {
    slug: 'soufriere',
    displayName: 'Soufriere',
    country: 'Saint Lucia',
    countryCode: 'LC',
    iana: 'America/St_Lucia',
    lat: 13.86,
    lng: -61.06,
    aliases: [],
    wikidataId: null,
    vibes: ['volcanic', 'lush', 'dramatic'],
    svgCitiesSlug: 'lc-soufriere',
  },
  {
    slug: 'granada-nicaragua',
    displayName: 'Granada',
    country: 'Nicaragua',
    countryCode: 'NI',
    iana: 'America/Managua',
    lat: 11.93,
    lng: -85.96,
    aliases: [],
    wikidataId: null,
    vibes: ['colonial', 'lakeside', 'colorful'],
    svgCitiesSlug: 'ni-granada',
  },
  {
    slug: 'panama-city',
    displayName: 'Panama City',
    country: 'Panama',
    countryCode: 'PA',
    iana: 'America/Panama',
    lat: 8.98,
    lng: -79.52,
    aliases: [],
    wikidataId: null,
    vibes: ['humid', 'cosmopolitan', 'gleaming'],
    svgCitiesSlug: 'pa-panama',
  },
  {
    slug: 'san-salvador',
    displayName: 'San Salvador',
    country: 'El Salvador',
    countryCode: 'SV',
    iana: 'America/El_Salvador',
    lat: 13.69,
    lng: -89.19,
    aliases: [],
    wikidataId: null,
    vibes: ['vibrant', 'resilient', 'volcanic'],
    svgCitiesSlug: 'sv-san-salvador',
  },
]

// --- Pre-computed lookup maps ---

const entityBySlug = new Map<string, CityEntity>()
const entityByDisplayName = new Map<string, CityEntity>()
const entityByAlias = new Map<string, CityEntity>()

for (const entity of CITY_ENTITIES) {
  entityBySlug.set(entity.slug, entity)
  entityByDisplayName.set(normalize(entity.displayName), entity)
  for (const alias of entity.aliases) {
    entityByAlias.set(alias.toLowerCase(), entity)
  }
}

// --- Exports ---

export function lookupEntity(input: string): CityEntity | null {
  const lower = input.toLowerCase().trim()
  const byAlias = entityByAlias.get(lower)
  if (byAlias) return byAlias
  const byName = entityByDisplayName.get(normalize(input))
  if (byName) return byName
  return null
}

export function getEntityBySlug(slug: string): CityEntity | null {
  return entityBySlug.get(slug) ?? null
}

export function getAllEntities(): readonly CityEntity[] {
  return CITY_ENTITIES
}

export function getVibes(slug: string): string[] | null {
  return entityBySlug.get(slug)?.vibes ?? null
}

export function getSvgCitiesSlug(entitySlug: string): string | null {
  return entityBySlug.get(entitySlug)?.svgCitiesSlug ?? null
}
