import { normalize } from './resolver'

export interface CityEntity {
  slug: string
  displayName: string
  country: string
  countryCode: string
  iana: string
  lat: number
  lng: number
  aliases: string[]
  wikidataId: string | null
  vibes: string[] | null
  svgCitiesSlug: string | null
}

const CITY_ENTITIES: readonly CityEntity[] = [
  // --- North America ---
  {
    slug: 'new-york',
    displayName: 'New York',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 40.75,
    lng: -73.98,
    aliases: ['nyc', 'ny'],
    wikidataId: null,
    vibes: ['electric', 'hustling', 'bold'],
    svgCitiesSlug: null,
  },
  {
    slug: 'los-angeles',
    displayName: 'Los Angeles',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 33.99,
    lng: -118.18,
    aliases: ['la'],
    wikidataId: null,
    vibes: ['laid-back', 'sun-kissed', 'dreamy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'chicago',
    displayName: 'Chicago',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 41.83,
    lng: -87.75,
    aliases: ['chi'],
    wikidataId: null,
    vibes: ['gritty', 'soulful', 'windswept'],
    svgCitiesSlug: null,
  },
  {
    slug: 'san-francisco',
    displayName: 'San Francisco',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 37.74,
    lng: -122.46,
    aliases: ['sf', 'san fran'],
    wikidataId: null,
    vibes: ['foggy', 'inventive', 'free-spirited'],
    svgCitiesSlug: null,
  },
  {
    slug: 'boston',
    displayName: 'Boston',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 42.33,
    lng: -71.07,
    aliases: ['bos'],
    wikidataId: null,
    vibes: ['scholarly', 'scrappy', 'storied'],
    svgCitiesSlug: null,
  },
  {
    slug: 'miami',
    displayName: 'Miami',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 25.79,
    lng: -80.22,
    aliases: ['mia'],
    wikidataId: null,
    vibes: ['tropical', 'electric', 'vivid'],
    svgCitiesSlug: null,
  },
  {
    slug: 'seattle',
    displayName: 'Seattle',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 47.57,
    lng: -122.34,
    aliases: ['sea'],
    wikidataId: null,
    vibes: ['cozy', 'caffeinated', 'misty'],
    svgCitiesSlug: null,
  },
  {
    slug: 'denver',
    displayName: 'Denver',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Denver',
    lat: 39.74,
    lng: -104.98,
    aliases: ['den'],
    wikidataId: null,
    vibes: ['alpine', 'outdoorsy', 'crisp'],
    svgCitiesSlug: null,
  },
  {
    slug: 'austin',
    displayName: 'Austin',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 30.27,
    lng: -97.74,
    aliases: ['aus'],
    wikidataId: null,
    vibes: ['weird', 'creative', 'hot'],
    svgCitiesSlug: null,
  },
  {
    slug: 'portland',
    displayName: 'Portland',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 45.52,
    lng: -122.68,
    aliases: ['pdx'],
    wikidataId: null,
    vibes: ['quirky', 'rainy', 'chill'],
    svgCitiesSlug: null,
  },
  {
    slug: 'dallas',
    displayName: 'Dallas',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 32.82,
    lng: -96.84,
    aliases: ['dfw'],
    wikidataId: null,
    vibes: ['big', 'brash', 'sprawling'],
    svgCitiesSlug: null,
  },
  {
    slug: 'houston',
    displayName: 'Houston',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 29.82,
    lng: -95.34,
    aliases: ['hou'],
    wikidataId: null,
    vibes: ['ambitious', 'sprawling', 'steamy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'atlanta',
    displayName: 'Atlanta',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 33.83,
    lng: -84.40,
    aliases: ['atl'],
    wikidataId: null,
    vibes: ['southern', 'buzzing', 'warm'],
    svgCitiesSlug: null,
  },
  {
    slug: 'las-vegas',
    displayName: 'Las Vegas',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Los_Angeles',
    lat: 36.21,
    lng: -115.22,
    aliases: ['vegas'],
    wikidataId: null,
    vibes: ['flashy', 'restless', 'neon'],
    svgCitiesSlug: null,
  },
  {
    slug: 'new-orleans',
    displayName: 'New Orleans',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 30.00,
    lng: -90.04,
    aliases: ['nola'],
    wikidataId: null,
    vibes: ['sultry', 'soulful', 'festive'],
    svgCitiesSlug: null,
  },
  {
    slug: 'minneapolis',
    displayName: 'Minneapolis',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Chicago',
    lat: 44.98,
    lng: -93.25,
    aliases: ['msp'],
    wikidataId: null,
    vibes: ['hardy', 'friendly', 'lakeside'],
    svgCitiesSlug: null,
  },
  {
    slug: 'detroit',
    displayName: 'Detroit',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Detroit',
    lat: 42.33,
    lng: -83.08,
    aliases: ['dtw'],
    wikidataId: null,
    vibes: ['resilient', 'gritty', 'reborn'],
    svgCitiesSlug: null,
  },
  {
    slug: 'philadelphia',
    displayName: 'Philadelphia',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 40.00,
    lng: -75.17,
    aliases: ['philly'],
    wikidataId: null,
    vibes: ['scrappy', 'proud', 'historic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'honolulu',
    displayName: 'Honolulu',
    country: 'USA',
    countryCode: 'US',
    iana: 'Pacific/Honolulu',
    lat: 21.31,
    lng: -157.86,
    aliases: [],
    wikidataId: null,
    vibes: ['aloha', 'breezy', 'golden'],
    svgCitiesSlug: null,
  },
  {
    slug: 'washington-dc',
    displayName: 'Washington DC',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/New_York',
    lat: 38.90,
    lng: -77.01,
    aliases: ['dc'],
    wikidataId: null,
    vibes: ['powerful', 'polished', 'monumental'],
    svgCitiesSlug: null,
  },
  {
    slug: 'anchorage',
    displayName: 'Anchorage',
    country: 'USA',
    countryCode: 'US',
    iana: 'America/Anchorage',
    lat: 61.22,
    lng: -149.90,
    aliases: [],
    wikidataId: null,
    vibes: ['wild', 'rugged', 'vast'],
    svgCitiesSlug: null,
  },
  {
    slug: 'toronto',
    displayName: 'Toronto',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Toronto',
    lat: 43.70,
    lng: -79.42,
    aliases: ['canada'],
    wikidataId: null,
    vibes: ['multicultural', 'polite', 'dynamic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'montreal',
    displayName: 'Montreal',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Montreal',
    lat: 45.50,
    lng: -73.58,
    aliases: [],
    wikidataId: null,
    vibes: ['bilingual', 'festive', 'artsy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'vancouver',
    displayName: 'Vancouver',
    country: 'Canada',
    countryCode: 'CA',
    iana: 'America/Vancouver',
    lat: 49.27,
    lng: -123.12,
    aliases: [],
    wikidataId: null,
    vibes: ['scenic', 'laid-back', 'lush'],
    svgCitiesSlug: null,
  },
  {
    slug: 'mexico-city',
    displayName: 'Mexico City',
    country: 'Mexico',
    countryCode: 'MX',
    iana: 'America/Mexico_City',
    lat: 19.44,
    lng: -99.13,
    aliases: ['cdmx', 'mexico'],
    wikidataId: null,
    vibes: ['vibrant', 'colorful', 'ancient'],
    svgCitiesSlug: null,
  },

  // --- South America ---
  {
    slug: 'sao-paulo',
    displayName: 'São Paulo',
    country: 'Brazil',
    countryCode: 'BR',
    iana: 'America/Sao_Paulo',
    lat: -23.56,
    lng: -46.63,
    aliases: ['brazil'],
    wikidataId: null,
    vibes: ['intense', 'rhythmic', 'massive'],
    svgCitiesSlug: null,
  },
  {
    slug: 'buenos-aires',
    displayName: 'Buenos Aires',
    country: 'Argentina',
    countryCode: 'AR',
    iana: 'America/Argentina/Buenos_Aires',
    lat: -34.60,
    lng: -58.40,
    aliases: ['argentina'],
    wikidataId: null,
    vibes: ['passionate', 'elegant', 'nocturnal'],
    svgCitiesSlug: null,
  },
  {
    slug: 'bogota',
    displayName: 'Bogota',
    country: 'Colombia',
    countryCode: 'CO',
    iana: 'America/Bogota',
    lat: 4.60,
    lng: -74.08,
    aliases: ['colombia'],
    wikidataId: null,
    vibes: ['warm', 'lively', 'elevated'],
    svgCitiesSlug: null,
  },
  {
    slug: 'lima',
    displayName: 'Lima',
    country: 'Peru',
    countryCode: 'PE',
    iana: 'America/Lima',
    lat: -12.05,
    lng: -77.05,
    aliases: ['peru'],
    wikidataId: null,
    vibes: ['misty', 'flavorful', 'ancient'],
    svgCitiesSlug: null,
  },
  {
    slug: 'santiago',
    displayName: 'Santiago',
    country: 'Chile',
    countryCode: 'CL',
    iana: 'America/Santiago',
    lat: -33.45,
    lng: -70.67,
    aliases: ['chile'],
    wikidataId: null,
    vibes: ['cosmopolitan', 'crisp', 'adventurous'],
    svgCitiesSlug: null,
  },

  // --- Europe ---
  {
    slug: 'london',
    displayName: 'London',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 51.50,
    lng: -0.12,
    aliases: ['uk', 'england'],
    wikidataId: null,
    vibes: ['posh', 'cozy', 'literary'],
    svgCitiesSlug: null,
  },
  {
    slug: 'paris',
    displayName: 'Paris',
    country: 'France',
    countryCode: 'FR',
    iana: 'Europe/Paris',
    lat: 48.87,
    lng: 2.33,
    aliases: ['france'],
    wikidataId: null,
    vibes: ['romantic', 'chic', 'dreamy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'berlin',
    displayName: 'Berlin',
    country: 'Germany',
    countryCode: 'DE',
    iana: 'Europe/Berlin',
    lat: 52.52,
    lng: 13.40,
    aliases: ['germany'],
    wikidataId: null,
    vibes: ['free', 'underground', 'raw'],
    svgCitiesSlug: null,
  },
  {
    slug: 'zurich',
    displayName: 'Zurich',
    country: 'Switzerland',
    countryCode: 'CH',
    iana: 'Europe/Zurich',
    lat: 47.38,
    lng: 8.55,
    aliases: ['switzerland'],
    wikidataId: null,
    vibes: ['precise', 'pristine', 'alpine'],
    svgCitiesSlug: null,
  },
  {
    slug: 'amsterdam',
    displayName: 'Amsterdam',
    country: 'Netherlands',
    countryCode: 'NL',
    iana: 'Europe/Amsterdam',
    lat: 52.35,
    lng: 4.92,
    aliases: ['netherlands', 'holland'],
    wikidataId: null,
    vibes: ['open-minded', 'breezy', 'candid'],
    svgCitiesSlug: null,
  },
  {
    slug: 'rome',
    displayName: 'Rome',
    country: 'Italy',
    countryCode: 'IT',
    iana: 'Europe/Rome',
    lat: 41.90,
    lng: 12.48,
    aliases: ['italy'],
    wikidataId: null,
    vibes: ['eternal', 'warm', 'dramatic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'madrid',
    displayName: 'Madrid',
    country: 'Spain',
    countryCode: 'ES',
    iana: 'Europe/Madrid',
    lat: 40.40,
    lng: -3.68,
    aliases: ['spain'],
    wikidataId: null,
    vibes: ['fiery', 'nocturnal', 'proud'],
    svgCitiesSlug: null,
  },
  {
    slug: 'lisbon',
    displayName: 'Lisbon',
    country: 'Portugal',
    countryCode: 'PT',
    iana: 'Europe/Lisbon',
    lat: 38.72,
    lng: -9.14,
    aliases: ['portugal'],
    wikidataId: null,
    vibes: ['melancholic', 'sunny', 'soulful'],
    svgCitiesSlug: null,
  },
  {
    slug: 'stockholm',
    displayName: 'Stockholm',
    country: 'Sweden',
    countryCode: 'SE',
    iana: 'Europe/Stockholm',
    lat: 59.35,
    lng: 18.10,
    aliases: ['sweden'],
    wikidataId: null,
    vibes: ['minimal', 'sleek', 'thoughtful'],
    svgCitiesSlug: null,
  },
  {
    slug: 'oslo',
    displayName: 'Oslo',
    country: 'Norway',
    countryCode: 'NO',
    iana: 'Europe/Oslo',
    lat: 59.92,
    lng: 10.75,
    aliases: ['norway'],
    wikidataId: null,
    vibes: ['rugged', 'quiet', 'pristine'],
    svgCitiesSlug: null,
  },
  {
    slug: 'copenhagen',
    displayName: 'Copenhagen',
    country: 'Denmark',
    countryCode: 'DK',
    iana: 'Europe/Copenhagen',
    lat: 55.68,
    lng: 12.57,
    aliases: ['denmark'],
    wikidataId: null,
    vibes: ['hygge', 'cozy', 'whimsical'],
    svgCitiesSlug: null,
  },
  {
    slug: 'helsinki',
    displayName: 'Helsinki',
    country: 'Finland',
    countryCode: 'FI',
    iana: 'Europe/Helsinki',
    lat: 60.18,
    lng: 24.93,
    aliases: ['finland'],
    wikidataId: null,
    vibes: ['stoic', 'serene', 'luminous'],
    svgCitiesSlug: null,
  },
  {
    slug: 'vienna',
    displayName: 'Vienna',
    country: 'Austria',
    countryCode: 'AT',
    iana: 'Europe/Vienna',
    lat: 48.20,
    lng: 16.37,
    aliases: ['austria'],
    wikidataId: null,
    vibes: ['refined', 'classical', 'grand'],
    svgCitiesSlug: null,
  },
  {
    slug: 'brussels',
    displayName: 'Brussels',
    country: 'Belgium',
    countryCode: 'BE',
    iana: 'Europe/Brussels',
    lat: 50.83,
    lng: 4.33,
    aliases: ['belgium'],
    wikidataId: null,
    vibes: ['cosmopolitan', 'quirky', 'indulgent'],
    svgCitiesSlug: null,
  },
  {
    slug: 'warsaw',
    displayName: 'Warsaw',
    country: 'Poland',
    countryCode: 'PL',
    iana: 'Europe/Warsaw',
    lat: 52.25,
    lng: 21.00,
    aliases: ['poland'],
    wikidataId: null,
    vibes: ['resilient', 'rising', 'spirited'],
    svgCitiesSlug: null,
  },
  {
    slug: 'prague',
    displayName: 'Prague',
    country: 'Czech Republic',
    countryCode: 'CZ',
    iana: 'Europe/Prague',
    lat: 50.08,
    lng: 14.47,
    aliases: ['czech republic', 'czechia'],
    wikidataId: null,
    vibes: ['bohemian', 'golden', 'enchanted'],
    svgCitiesSlug: null,
  },
  {
    slug: 'athens',
    displayName: 'Athens',
    country: 'Greece',
    countryCode: 'GR',
    iana: 'Europe/Athens',
    lat: 37.98,
    lng: 23.73,
    aliases: ['greece'],
    wikidataId: null,
    vibes: ['ancient', 'sun-drenched', 'philosophical'],
    svgCitiesSlug: null,
  },
  {
    slug: 'istanbul',
    displayName: 'Istanbul',
    country: 'Turkey',
    countryCode: 'TR',
    iana: 'Europe/Istanbul',
    lat: 41.10,
    lng: 29.01,
    aliases: ['turkey'],
    wikidataId: null,
    vibes: ['mystical', 'bustling', 'layered'],
    svgCitiesSlug: null,
  },
  {
    slug: 'moscow',
    displayName: 'Moscow',
    country: 'Russia',
    countryCode: 'RU',
    iana: 'Europe/Moscow',
    lat: 55.75,
    lng: 37.62,
    aliases: ['russia'],
    wikidataId: null,
    vibes: ['imposing', 'wintry', 'grand'],
    svgCitiesSlug: null,
  },
  {
    slug: 'dublin',
    displayName: 'Dublin',
    country: 'Ireland',
    countryCode: 'IE',
    iana: 'Europe/Dublin',
    lat: 53.33,
    lng: -6.25,
    aliases: ['ireland'],
    wikidataId: null,
    vibes: ['convivial', 'witty', 'rainy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'edinburgh',
    displayName: 'Edinburgh',
    country: 'United Kingdom',
    countryCode: 'GB',
    iana: 'Europe/London',
    lat: 55.95,
    lng: -3.22,
    aliases: ['scotland'],
    wikidataId: null,
    vibes: ['moody', 'storied', 'misty'],
    svgCitiesSlug: null,
  },
  {
    slug: 'reykjavik',
    displayName: 'Reykjavik',
    country: 'Iceland',
    countryCode: 'IS',
    iana: 'Atlantic/Reykjavik',
    lat: 64.15,
    lng: -21.95,
    aliases: [],
    wikidataId: null,
    vibes: ['otherworldly', 'stark', 'luminous'],
    svgCitiesSlug: null,
  },

  // --- Africa ---
  {
    slug: 'cairo',
    displayName: 'Cairo',
    country: 'Egypt',
    countryCode: 'EG',
    iana: 'Africa/Cairo',
    lat: 30.05,
    lng: 31.25,
    aliases: ['egypt'],
    wikidataId: null,
    vibes: ['ancient', 'chaotic', 'timeless'],
    svgCitiesSlug: null,
  },
  {
    slug: 'johannesburg',
    displayName: 'Johannesburg',
    country: 'South Africa',
    countryCode: 'ZA',
    iana: 'Africa/Johannesburg',
    lat: -26.17,
    lng: 28.03,
    aliases: ['south africa'],
    wikidataId: null,
    vibes: ['ambitious', 'golden', 'resilient'],
    svgCitiesSlug: null,
  },
  {
    slug: 'cape-town',
    displayName: 'Cape Town',
    country: 'South Africa',
    countryCode: 'ZA',
    iana: 'Africa/Johannesburg',
    lat: -33.92,
    lng: 18.43,
    aliases: [],
    wikidataId: null,
    vibes: ['stunning', 'breezy', 'wild'],
    svgCitiesSlug: null,
  },
  {
    slug: 'lagos',
    displayName: 'Lagos',
    country: 'Nigeria',
    countryCode: 'NG',
    iana: 'Africa/Lagos',
    lat: 6.44,
    lng: 3.39,
    aliases: ['nigeria'],
    wikidataId: null,
    vibes: ['hustling', 'loud', 'unstoppable'],
    svgCitiesSlug: null,
  },
  {
    slug: 'nairobi',
    displayName: 'Nairobi',
    country: 'Kenya',
    countryCode: 'KE',
    iana: 'Africa/Nairobi',
    lat: -1.28,
    lng: 36.82,
    aliases: ['kenya'],
    wikidataId: null,
    vibes: ['enterprising', 'sunny', 'rising'],
    svgCitiesSlug: null,
  },

  // --- Middle East ---
  {
    slug: 'dubai',
    displayName: 'Dubai',
    country: 'United Arab Emirates',
    countryCode: 'AE',
    iana: 'Asia/Dubai',
    lat: 25.23,
    lng: 55.28,
    aliases: ['uae'],
    wikidataId: null,
    vibes: ['opulent', 'futuristic', 'dazzling'],
    svgCitiesSlug: null,
  },
  {
    slug: 'riyadh',
    displayName: 'Riyadh',
    country: 'Saudi Arabia',
    countryCode: 'SA',
    iana: 'Asia/Riyadh',
    lat: 24.64,
    lng: 46.77,
    aliases: ['saudi arabia'],
    wikidataId: null,
    vibes: ['vast', 'ambitious', 'scorching'],
    svgCitiesSlug: null,
  },
  {
    slug: 'jerusalem',
    displayName: 'Jerusalem',
    country: 'Israel',
    countryCode: 'IL',
    iana: 'Asia/Jerusalem',
    lat: 31.78,
    lng: 35.21,
    aliases: ['israel'],
    wikidataId: null,
    vibes: ['sacred', 'ancient', 'layered'],
    svgCitiesSlug: null,
  },

  // --- Asia ---
  {
    slug: 'tokyo',
    displayName: 'Tokyo',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 35.69,
    lng: 139.75,
    aliases: ['japan'],
    wikidataId: null,
    vibes: ['zen', 'precise', 'futuristic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'osaka',
    displayName: 'Osaka',
    country: 'Japan',
    countryCode: 'JP',
    iana: 'Asia/Tokyo',
    lat: 34.75,
    lng: 135.46,
    aliases: [],
    wikidataId: null,
    vibes: ['playful', 'flavorful', 'neon'],
    svgCitiesSlug: null,
  },
  {
    slug: 'seoul',
    displayName: 'Seoul',
    country: 'South Korea',
    countryCode: 'KR',
    iana: 'Asia/Seoul',
    lat: 37.57,
    lng: 127.00,
    aliases: ['korea', 'south korea'],
    wikidataId: null,
    vibes: ['trendy', 'fast-paced', 'glossy'],
    svgCitiesSlug: null,
  },
  {
    slug: 'shanghai',
    displayName: 'Shanghai',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 31.22,
    lng: 121.44,
    aliases: ['china'],
    wikidataId: null,
    vibes: ['electric', 'towering', 'relentless'],
    svgCitiesSlug: null,
  },
  {
    slug: 'beijing',
    displayName: 'Beijing',
    country: 'China',
    countryCode: 'CN',
    iana: 'Asia/Shanghai',
    lat: 39.93,
    lng: 116.39,
    aliases: [],
    wikidataId: null,
    vibes: ['imperial', 'vast', 'storied'],
    svgCitiesSlug: null,
  },
  {
    slug: 'hong-kong',
    displayName: 'Hong Kong',
    country: 'Hong Kong',
    countryCode: 'HK',
    iana: 'Asia/Hong_Kong',
    lat: 22.30,
    lng: 114.19,
    aliases: ['hk'],
    wikidataId: null,
    vibes: ['dense', 'neon', 'kinetic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'singapore',
    displayName: 'Singapore',
    country: 'Singapore',
    countryCode: 'SG',
    iana: 'Asia/Singapore',
    lat: 1.29,
    lng: 103.86,
    aliases: ['sg'],
    wikidataId: null,
    vibes: ['orderly', 'lush', 'spotless'],
    svgCitiesSlug: null,
  },
  {
    slug: 'bangkok',
    displayName: 'Bangkok',
    country: 'Thailand',
    countryCode: 'TH',
    iana: 'Asia/Bangkok',
    lat: 13.75,
    lng: 100.52,
    aliases: ['bkk', 'thailand'],
    wikidataId: null,
    vibes: ['steamy', 'chaotic', 'golden'],
    svgCitiesSlug: null,
  },
  {
    slug: 'mumbai',
    displayName: 'Mumbai',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 19.02,
    lng: 72.86,
    aliases: ['india'],
    wikidataId: null,
    vibes: ['intense', 'cinematic', 'teeming'],
    svgCitiesSlug: null,
  },
  {
    slug: 'delhi',
    displayName: 'Delhi',
    country: 'India',
    countryCode: 'IN',
    iana: 'Asia/Kolkata',
    lat: 28.67,
    lng: 77.23,
    aliases: [],
    wikidataId: null,
    vibes: ['spicy', 'historic', 'vibrant'],
    svgCitiesSlug: null,
  },
  {
    slug: 'karachi',
    displayName: 'Karachi',
    country: 'Pakistan',
    countryCode: 'PK',
    iana: 'Asia/Karachi',
    lat: 24.87,
    lng: 66.99,
    aliases: ['pakistan'],
    wikidataId: null,
    vibes: ['gritty', 'sprawling', 'spirited'],
    svgCitiesSlug: null,
  },
  {
    slug: 'dhaka',
    displayName: 'Dhaka',
    country: 'Bangladesh',
    countryCode: 'BD',
    iana: 'Asia/Dhaka',
    lat: 23.72,
    lng: 90.41,
    aliases: ['bangladesh'],
    wikidataId: null,
    vibes: ['dense', 'lively', 'colorful'],
    svgCitiesSlug: null,
  },
  {
    slug: 'ho-chi-minh-city',
    displayName: 'Ho Chi Minh City',
    country: 'Vietnam',
    countryCode: 'VN',
    iana: 'Asia/Ho_Chi_Minh',
    lat: 10.78,
    lng: 106.70,
    aliases: ['vietnam'],
    wikidataId: null,
    vibes: ['buzzing', 'aromatic', 'warm'],
    svgCitiesSlug: null,
  },
  {
    slug: 'jakarta',
    displayName: 'Jakarta',
    country: 'Indonesia',
    countryCode: 'ID',
    iana: 'Asia/Jakarta',
    lat: -6.17,
    lng: 106.83,
    aliases: ['indonesia'],
    wikidataId: null,
    vibes: ['tropical', 'sprawling', 'lively'],
    svgCitiesSlug: null,
  },
  {
    slug: 'kuala-lumpur',
    displayName: 'Kuala Lumpur',
    country: 'Malaysia',
    countryCode: 'MY',
    iana: 'Asia/Kuala_Lumpur',
    lat: 3.17,
    lng: 101.70,
    aliases: ['malaysia'],
    wikidataId: null,
    vibes: ['gleaming', 'tropical', 'diverse'],
    svgCitiesSlug: null,
  },
  {
    slug: 'manila',
    displayName: 'Manila',
    country: 'Philippines',
    countryCode: 'PH',
    iana: 'Asia/Manila',
    lat: 14.60,
    lng: 120.98,
    aliases: ['philippines'],
    wikidataId: null,
    vibes: ['cheerful', 'resilient', 'warm'],
    svgCitiesSlug: null,
  },
  {
    slug: 'taipei',
    displayName: 'Taipei',
    country: 'Taiwan',
    countryCode: 'TW',
    iana: 'Asia/Taipei',
    lat: 25.04,
    lng: 121.57,
    aliases: ['taiwan'],
    wikidataId: null,
    vibes: ['inventive', 'nocturnal', 'sweet'],
    svgCitiesSlug: null,
  },
  {
    slug: 'kathmandu',
    displayName: 'Kathmandu',
    country: 'Nepal',
    countryCode: 'NP',
    iana: 'Asia/Kathmandu',
    lat: 27.72,
    lng: 85.32,
    aliases: [],
    wikidataId: null,
    vibes: ['spiritual', 'high', 'serene'],
    svgCitiesSlug: null,
  },

  // --- Oceania ---
  {
    slug: 'sydney',
    displayName: 'Sydney',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Sydney',
    lat: -33.92,
    lng: 151.19,
    aliases: ['australia'],
    wikidataId: null,
    vibes: ['sunny', 'sparkling', 'coastal'],
    svgCitiesSlug: null,
  },
  {
    slug: 'melbourne',
    displayName: 'Melbourne',
    country: 'Australia',
    countryCode: 'AU',
    iana: 'Australia/Melbourne',
    lat: -37.82,
    lng: 144.98,
    aliases: [],
    wikidataId: null,
    vibes: ['artsy', 'caffeinated', 'eclectic'],
    svgCitiesSlug: null,
  },
  {
    slug: 'auckland',
    displayName: 'Auckland',
    country: 'New Zealand',
    countryCode: 'NZ',
    iana: 'Pacific/Auckland',
    lat: -36.85,
    lng: 174.76,
    aliases: ['new zealand', 'nz'],
    wikidataId: null,
    vibes: ['adventurous', 'green', 'fresh'],
    svgCitiesSlug: null,
  },
]

// --- Pre-computed lookup maps ---

const entityBySlug = new Map<string, CityEntity>()
const entityByDisplayName = new Map<string, CityEntity>()
const entityByAlias = new Map<string, CityEntity>()

for (const entity of CITY_ENTITIES) {
  entityBySlug.set(entity.slug, entity)
  entityByDisplayName.set(normalize(entity.displayName), entity)
  for (const alias of entity.aliases) {
    entityByAlias.set(alias.toLowerCase(), entity)
  }
}

// --- Exports ---

export function lookupEntity(input: string): CityEntity | null {
  const lower = input.toLowerCase().trim()
  const byAlias = entityByAlias.get(lower)
  if (byAlias) return byAlias
  const byName = entityByDisplayName.get(normalize(input))
  if (byName) return byName
  return null
}

export function getEntityBySlug(slug: string): CityEntity | null {
  return entityBySlug.get(slug) ?? null
}

export function getAllEntities(): readonly CityEntity[] {
  return CITY_ENTITIES
}

export function getVibes(slug: string): string[] | null {
  return entityBySlug.get(slug)?.vibes ?? null
}
