export const CONNECTORS = new Set(['in', 'to', '→', '->', 'at', '=>', 'from'])

/** Common timezone abbreviations -> IANA timezone */
export const TZ_ABBREVIATIONS: Record<string, string> = {
  // Americas
  'est': 'America/New_York',
  'edt': 'America/New_York',
  'et': 'America/New_York',
  'cst': 'America/Chicago',
  'cdt': 'America/Chicago',
  'ct': 'America/Chicago',
  'mst': 'America/Denver',
  'mdt': 'America/Denver',
  'mt': 'America/Denver',
  'pst': 'America/Los_Angeles',
  'pdt': 'America/Los_Angeles',
  'pt': 'America/Los_Angeles',
  'akst': 'America/Anchorage',
  'akdt': 'America/Anchorage',
  'hst': 'Pacific/Honolulu',
  'ast': 'America/Halifax',
  'adt': 'America/Halifax',
  // Europe
  'gmt': 'Europe/London',
  'bst': 'Europe/London',
  'utc': 'UTC',
  'wet': 'Europe/Lisbon',
  'west': 'Europe/Lisbon',
  'cet': 'Europe/Paris',
  'cest': 'Europe/Paris',
  'eet': 'Europe/Helsinki',
  'eest': 'Europe/Helsinki',
  'msk': 'Europe/Moscow',
  // Asia
  'ist': 'Asia/Kolkata',
  'jst': 'Asia/Tokyo',
  'kst': 'Asia/Seoul',
  'hkt': 'Asia/Hong_Kong',
  'sgt': 'Asia/Singapore',
  'ict': 'Asia/Bangkok',
  'pht': 'Asia/Manila',
  // Oceania
  'aest': 'Australia/Sydney',
  'aedt': 'Australia/Sydney',
  'acst': 'Australia/Adelaide',
  'acdt': 'Australia/Adelaide',
  'awst': 'Australia/Perth',
  'nzst': 'Pacific/Auckland',
  'nzdt': 'Pacific/Auckland',
}

export const NAMED_TIMES: Record<string, { hour: number; minute: number }> = {
  'midnight': { hour: 0, minute: 0 },
  'noon': { hour: 12, minute: 0 },
  'midday': { hour: 12, minute: 0 },
}

export const DATE_MODIFIERS: Record<string, 'tomorrow' | 'yesterday' | 'today'> = {
  'tomorrow': 'tomorrow',
  'tmrw': 'tomorrow',
  'tmw': 'tomorrow',
  'yesterday': 'yesterday',
  'today': 'today',
}

export const TZ_ABBREVIATION_LABELS: Record<string, string> = {
  'est': 'US Eastern Time',
  'edt': 'US Eastern Time',
  'et': 'US Eastern Time',
  'cst': 'US Central Time',
  'cdt': 'US Central Time',
  'ct': 'US Central Time',
  'mst': 'US Mountain Time',
  'mdt': 'US Mountain Time',
  'mt': 'US Mountain Time',
  'pst': 'US Pacific Time',
  'pdt': 'US Pacific Time',
  'pt': 'US Pacific Time',
  'akst': 'Alaska Time',
  'akdt': 'Alaska Time',
  'hst': 'Hawaii Time',
  'ast': 'Atlantic Time',
  'adt': 'Atlantic Time',
  'gmt': 'Greenwich Mean Time',
  'bst': 'British Summer Time',
  'utc': 'Coordinated Universal Time',
  'wet': 'Western European Time',
  'west': 'Western European Summer Time',
  'cet': 'Central European Time',
  'cest': 'Central European Summer Time',
  'eet': 'Eastern European Time',
  'eest': 'Eastern European Summer Time',
  'msk': 'Moscow Time',
  'ist': 'India Standard Time',
  'jst': 'Japan Standard Time',
  'kst': 'Korea Standard Time',
  'hkt': 'Hong Kong Time',
  'sgt': 'Singapore Time',
  'ict': 'Indochina Time',
  'pht': 'Philippine Time',
  'aest': 'Australian Eastern Time',
  'aedt': 'Australian Eastern Time',
  'acst': 'Australian Central Time',
  'acdt': 'Australian Central Time',
  'awst': 'Australian Western Time',
  'nzst': 'New Zealand Time',
  'nzdt': 'New Zealand Time',
}
