/**
 * Re-encodes `city-timezones` into the form the app ships: positional records
 * with timezone, country and province lifted into lookup tables. 241 KB gzipped
 * becomes 119 KB for the same rows.
 *
 * Two blobs come out, split on population. Decoder: `src/engine/city-table.ts`.
 * Output must stay a pure function of the pinned package — `vendor.test.ts`
 * regenerates and compares.
 */

import cityTimezones from 'city-timezones'
import { join } from 'node:path'

const ENGINE = join(import.meta.dirname, '..', '..', 'src', 'engine')

export const OUTPUT_FILE = join(ENGINE, 'city-data.generated.ts')

/** Its own module, so the bundler gives the tail its own chunk. */
export const TAIL_OUTPUT_FILE = join(ENGINE, 'city-data-tail.generated.ts')

/** Rows at or above this population are bundled; the rest load on demand. */
export const HEAD_MIN_POP = 100_000

/** Split on the decoded value, so the head matches what the decoder reports. */
function decodedPop(r: RawRow): number {
  return r.pop ? Math.round(r.pop / POP_UNIT) * POP_UNIT : 0
}

/** Population is carried in thousands, which is finer than anything reads it. */
const POP_UNIT = 1000

/** Coordinates are carried as hundredths of a degree — about 1.1 km. */
const COORD_SCALE = 100

const FIELD = '\t'
const ROW = '\n'

interface RawRow {
  city: string
  city_ascii: string
  lat: number
  lng: number
  pop: number
  country: string
  iso2: string | number
  iso3: string
  province: string
  timezone: string
}

/** A row with no zone would resolve to `iana: null`. */
export function sourceRows(): RawRow[] {
  return (cityTimezones.cityMapping as unknown as RawRow[]).filter(
    (r) => typeof r.timezone === 'string' && r.timezone.length > 0,
  )
}

function encode(rows: RawRow[]): string {
  const zones = index(rows.map((r) => r.timezone))
  // iso2 and iso3 travel with the country name except across France's overseas
  // departments, so the three share one entry.
  const countries = index(rows.map((r) => `${r.country}|${isoTwo(r)}|${r.iso3}`))
  const provinces = index(rows.map((r) => r.province))

  const lines = rows.map((r) =>
    [
      r.city,
      // 103 rows spell the two names differently; the rest cost an empty field.
      r.city_ascii === r.city ? '' : r.city_ascii,
      base36(countries.get(`${r.country}|${isoTwo(r)}|${r.iso3}`)!),
      base36(provinces.get(r.province)!),
      base36(zones.get(r.timezone)!),
      base36(Math.round(r.lat * COORD_SCALE) + 90 * COORD_SCALE),
      base36(Math.round(r.lng * COORD_SCALE) + 180 * COORD_SCALE),
      r.pop ? base36(Math.round(r.pop / POP_UNIT)) : '',
    ].join(FIELD),
  )

  return [
    [...zones.keys()].join(FIELD),
    [...countries.keys()].join(FIELD),
    [...provinces.keys()].join(FIELD),
    lines.join(ROW),
  ].join(ROW)
}

/** 8 rows carry `-99` where an ISO code belongs. */
function isoTwo(r: RawRow): string {
  return typeof r.iso2 === 'string' ? r.iso2 : ''
}

function index(values: string[]): Map<string, number> {
  const map = new Map<string, number>()
  for (const v of values) if (!map.has(v)) map.set(v, map.size)
  return map
}

function base36(n: number): string {
  return n.toString(36)
}

/**
 * A template literal holds the blob verbatim; quoting would escape a byte per
 * delimiter across 58,000 fields. Nine city names carry a backtick.
 */
function asTemplateLiteral(blob: string): string {
  return '`' + blob.replace(/[\\`]/g, '\\$&').replace(/\$\{/g, '\\${') + '`'
}

export interface CityDataResult {
  text: string
  tailText: string
  headRows: number
  tailRows: number
}

function header(rows: number): string[] {
  return [
    '// AUTO-GENERATED by scripts/generate-city-data.ts. Do not edit by hand.',
    `// Source: city-timezones, pinned in vendor/manifest.json. ${rows} rows in all.`,
    '// Encoding: scripts/lib/city-table.ts. Decoder: src/engine/city-table.ts.',
    '// To regenerate: npm run cities:generate',
    '',
  ]
}

export function generateCityData(): CityDataResult {
  const rows = sourceRows()
  const head = rows.filter((r) => decodedPop(r) >= HEAD_MIN_POP)
  const tail = rows.filter((r) => decodedPop(r) < HEAD_MIN_POP)
  const floor = HEAD_MIN_POP.toLocaleString('en-US')

  const text = [
    ...header(rows.length),
    `/** ${head.length} cities of ${floor} people or more, bundled. */`,
    `export const CITY_HEAD = ${asTemplateLiteral(encode(head))}`,
    '',
  ].join('\n')

  const tailText = [
    ...header(rows.length),
    `/** The ${tail.length} cities under ${floor} people. Imported on demand. */`,
    `export const CITY_TAIL = ${asTemplateLiteral(encode(tail))}`,
    '',
  ].join('\n')

  return { text, tailText, headRows: head.length, tailRows: tail.length }
}
